// Barrel exports: keep existing import style `from '@/lib/api'`
export { authApi } from '@/features/auth/services/auth';
export { businessApi } from './apis/business';
export { outletApi } from './apis/outlet';
export { productApi } from './apis/product';
export { stockApi } from './apis/stock';
export { orderApi } from './apis/order';
export { expenseApi } from './apis/expense';
export { withdrawalApi } from './apis/withdrawal';
export { dashboardApi } from './apis/dashboard';
export { businessDashboardApi } from './apis/business-dashboard';
export { uploadApi } from './apis/upload';
export { outletManagementApi } from './apis/outletManagement';
export { userApi } from './apis/user';
export { transactionApi } from './apis/transaction';
export { staffApi } from './apis/staff';
export { outletTransferApi } from './apis/outletTransfer';
export { tableApi } from './apis/table';
export { productCategoryApi } from './apis/product-category';
export type { ProductCategory } from './apis/product-category';
