services:
  postgres:
    container_name: "boss_db_container"
    image: postgres:15.12-alpine3.21
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: pitok
      POSTGRES_PASSWORD: pitok234
      POSTGRES_DB: boss_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "4444:4444"
    depends_on:
      - postgres
    environment:
      - NODE_ENV="development"
      - DATABASE_URL=postgresql://pitok:pitok234@postgres:5432/kmipn_db
      - BASE_URL=https://boss-api.pitok.my.id # backend ip atau backend domain
      - FRONTEND_URL=http://192.168.221.41:3333 # sesuaikan
      - PORT=2222
      - JWT_SECRET=rahasia-banget-ini-mah # ganti samo yang lebih kuat
