export default defineEventHandler(async (event) => {
  const query = getQuery(event);
  const limit = query.limit ? parseInt(query.limit as string) : undefined;
  const search = query.search as string || '';

  // Simulate API delay
  await new Promise((resolve) => setTimeout(resolve, 1000));

  const business = [
    {
      id: '1',
      name: 'Acme Corp',
      description: 'Leading retailer in Indonesia',
      createdAt: new Date(),
      updatedAt: new Date(),
      bankName: 'Bank Central Asia',
      bankAccount: '1234567890',
      accountHolder: 'John Doe',
      ownerId: '1',
      defaultTransactionFeeBearer: 'OWNER',
      wallet: undefined,
      memberships: []
    },
    {
      id: '2',
      name: 'Beta Mart',
      description: 'Convenience store chain',
      createdAt: new Date(),
      updatedAt: new Date(),
      bankName: 'Bank Mandiri',
      bankAccount: '9876543210',
      accountHolder: 'Jane Smith',
      ownerId: '2',
      defaultTransactionFeeBearer: 'BUSINESS',
      wallet: undefined,
      memberships: []
    },
    {
      id: '3',
      name: 'Gamma Electronics',
      description: 'Electronics and gadgets store',
      createdAt: new Date(),
      updatedAt: new Date(),
      bankName: 'Bank Negara Indonesia',
      bankAccount: '1122334455',
      accountHolder: 'Robert Johnson',
      ownerId: '3',
      defaultTransactionFeeBearer: 'OWNER',
      wallet: undefined,
      memberships: []
    },
    {
      id: '4',
      name: 'Delta Fashion',
      description: 'Trendy clothing and accessories',
      createdAt: new Date(),
      updatedAt: new Date(),
      bankName: 'Bank Rakyat Indonesia',
      bankAccount: '5566778899',
      accountHolder: 'Sarah Williams',
      ownerId: '4',
      defaultTransactionFeeBearer: 'BUSINESS',
      wallet: undefined,
      memberships: []
    },
    {
      id: '5',
      name: 'Epsilon Food Court',
      description: 'Various food stalls and restaurants',
      createdAt: new Date(),
      updatedAt: new Date(),
      bankName: 'Bank Danamon',
      bankAccount: '9988776655',
      accountHolder: 'Michael Brown',
      ownerId: '5',
      defaultTransactionFeeBearer: 'OWNER',
      wallet: undefined,
      memberships: []
    }
  ];

  const outlets = [
    // Acme Corp outlets
    {
      id: "1",
      name: "Acme Main Store",
      address: "Jl. Sudirman No. 123, Jakarta Selatan",
      phone: "+6281234567890",
      businessId: "1",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUD3RvDNL0Idc4lwUBfhbE7nFpjRwCJqD3HQ&s",
      createdAt: new Date(),
      updatedAt: new Date(),
      business: business[0],
    },
    {
      id: "2",
      name: "Acme Branch Thamrin",
      address: "Jl. Thamrin No. 456, Jakarta Pusat",
      phone: "+6281234567891",
      businessId: "1",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSz9uJiPPaqjtr6F0-R_Nbsd19TyBWiRI9SuA&s",
      createdAt: new Date(),
      updatedAt: new Date(),
      business: business[0],
    },
    {
      id: "3",
      name: "Acme Kelapa Gading",
      address: "Jl. Kelapa Gading No. 789, Jakarta Utara",
      phone: "+6281234567892",
      businessId: "1",
      image: null,
      createdAt: new Date(),
      updatedAt: new Date(),
      business: business[0],
    },
    {
      id: "4",
      name: "Acme Pondok Indah",
      address: "Jl. Metro Pondok Indah No. 101, Jakarta Selatan",
      phone: "+6281234567893",
      businessId: "1",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxpVkU6L_4FB2LGueJ_QPdT_vuibIvbTiPDQ&s",
      createdAt: new Date(),
      updatedAt: new Date(),
      business: business[0],
    },
    
    // Beta Mart outlets
    {
      id: "5",
      name: "Beta Mart Central",
      address: "Jl. Gatot Subroto No. 234, Jakarta Selatan",
      phone: "+6281234567894",
      businessId: "2",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUD3RvDNL0Idc4lwUBfhbE7nFpjRwCJqD3HQ&s",
      createdAt: new Date(),
      updatedAt: new Date(),
      business: business[1],
    },
    {
      id: "6",
      name: "Beta Mart Kemang",
      address: "Jl. Kemang Raya No. 567, Jakarta Selatan",
      phone: "+6281234567895",
      businessId: "2",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSz9uJiPPaqjtr6F0-R_Nbsd19TyBWiRI9SuA&s",
      createdAt: new Date(),
      updatedAt: new Date(),
      business: business[1],
    },
    {
      id: "7",
      name: "Beta Mart Menteng",
      address: "Jl. Menteng No. 890, Jakarta Pusat",
      phone: "+6281234567896",
      businessId: "2",
      image: null,
      createdAt: new Date(),
      updatedAt: new Date(),
      business: business[1],
    },
    {
      id: "8",
      name: "Beta Mart Kuningan",
      address: "Jl. Kuningan No. 321, Jakarta Selatan",
      phone: "+6281234567897",
      businessId: "2",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxpVkU6L_4FB2LGueJ_QPdT_vuibIvbTiPDQ&s",
      createdAt: new Date(),
      updatedAt: new Date(),
      business: business[1],
    },
    {
      id: "9",
      name: "Beta Mart Senayan",
      address: "Jl. Senayan No. 654, Jakarta Selatan",
      phone: "+6281234567898",
      businessId: "2",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUD3RvDNL0Idc4lwUBfhbE7nFpjRwCJqD3HQ&s",
      createdAt: new Date(),
      updatedAt: new Date(),
      business: business[1],
    },

    // Gamma Electronics outlets
    {
      id: "10",
      name: "Gamma Electronics Plaza Indonesia",
      address: "Plaza Indonesia, Jl. Thamrin No. 28-30, Jakarta Pusat",
      phone: "+6281234567899",
      businessId: "3",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSz9uJiPPaqjtr6F0-R_Nbsd19TyBWiRI9SuA&s",
      createdAt: new Date(),
      updatedAt: new Date(),
      business: business[2],
    },
    {
      id: "11",
      name: "Gamma Electronics Mangga Dua",
      address: "Mangga Dua Mall, Jl. Mangga Dua Raya, Jakarta Utara",
      phone: "+6281234567900",
      businessId: "3",
      image: null,
      createdAt: new Date(),
      updatedAt: new Date(),
      business: business[2],
    },
    {
      id: "12",
      name: "Gamma Electronics Blok M",
      address: "Blok M Square, Jl. Melawai No. 185, Jakarta Selatan",
      phone: "+6281234567901",
      businessId: "3",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxpVkU6L_4FB2LGueJ_QPdT_vuibIvbTiPDQ&s",
      createdAt: new Date(),
      updatedAt: new Date(),
      business: business[2],
    },
    {
      id: "13",
      name: "Gamma Electronics Cempaka Putih",
      address: "Jl. Cempaka Putih No. 147, Jakarta Pusat",
      phone: "+6281234567902",
      businessId: "3",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUD3RvDNL0Idc4lwUBfhbE7nFpjRwCJqD3HQ&s",
      createdAt: new Date(),
      updatedAt: new Date(),
      business: business[2],
    },

    // Delta Fashion outlets
    {
      id: "14",
      name: "Delta Fashion Grand Indonesia",
      address: "Grand Indonesia Mall, Jl. Thamrin No. 1, Jakarta Pusat",
      phone: "+6281234567903",
      businessId: "4",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSz9uJiPPaqjtr6F0-R_Nbsd19TyBWiRI9SuA&s",
      createdAt: new Date(),
      updatedAt: new Date(),
      business: business[3],
    },
    {
      id: "15",
      name: "Delta Fashion Senayan City",
      address: "Senayan City Mall, Jl. Asia Afrika No. 8, Jakarta Selatan",
      phone: "+6281234567904",
      businessId: "4",
      image: null,
      createdAt: new Date(),
      updatedAt: new Date(),
      business: business[3],
    },
    {
      id: "16",
      name: "Delta Fashion Kota Kasablanka",
      address: "Kota Kasablanka Mall, Jl. Casablanca No. 88, Jakarta Selatan",
      phone: "+6281234567905",
      businessId: "4",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxpVkU6L_4FB2LGueJ_QPdT_vuibIvbTiPDQ&s",
      createdAt: new Date(),
      updatedAt: new Date(),
      business: business[3],
    },
    {
      id: "17",
      name: "Delta Fashion Central Park",
      address: "Central Park Mall, Jl. Letjen S. Parman No. 28, Jakarta Barat",
      phone: "+6281234567906",
      businessId: "4",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUD3RvDNL0Idc4lwUBfhbE7nFpjRwCJqD3HQ&s",
      createdAt: new Date(),
      updatedAt: new Date(),
      business: business[3],
    },
    {
      id: "18",
      name: "Delta Fashion PIK Avenue",
      address: "PIK Avenue Mall, Jl. Pantai Indah Kapuk, Jakarta Utara",
      phone: "+6281234567907",
      businessId: "4",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSz9uJiPPaqjtr6F0-R_Nbsd19TyBWiRI9SuA&s",
      createdAt: new Date(),
      updatedAt: new Date(),
      business: business[3],
    },

    // Epsilon Food Court outlets
    {
      id: "19",
      name: "Epsilon Food Court Sarinah",
      address: "Sarinah Building, Jl. Thamrin No. 11, Jakarta Pusat",
      phone: "+6281234567908",
      businessId: "5",
      image: null,
      createdAt: new Date(),
      updatedAt: new Date(),
      business: business[4],
    },
    {
      id: "20",
      name: "Epsilon Food Court Pasar Festival",
      address: "Pasar Festival Mall, Jl. HR Rasuna Said, Jakarta Selatan",
      phone: "+6281234567909",
      businessId: "5",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxpVkU6L_4FB2LGueJ_QPdT_vuibIvbTiPDQ&s",
      createdAt: new Date(),
      updatedAt: new Date(),
      business: business[4],
    },
    {
      id: "21",
      name: "Epsilon Food Court Kelapa Gading Mall",
      address: "Kelapa Gading Mall, Jl. Kelapa Gading No. 1, Jakarta Utara",
      phone: "+6281234567910",
      businessId: "5",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUD3RvDNL0Idc4lwUBfhbE7nFpjRwCJqD3HQ&s",
      createdAt: new Date(),
      updatedAt: new Date(),
      business: business[4],
    },
    {
      id: "22",
      name: "Epsilon Food Court Lippo Mall",
      address: "Lippo Mall Kemang, Jl. Kemang Timur No. 1, Jakarta Selatan",
      phone: "+6281234567911",
      businessId: "5",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSz9uJiPPaqjtr6F0-R_Nbsd19TyBWiRI9SuA&s",
      createdAt: new Date(),
      updatedAt: new Date(),
      business: business[4],
    },
    {
      id: "23",
      name: "Epsilon Food Court Artha Gading",
      address: "Artha Gading Mall, Jl. Artha Gading No. 1, Jakarta Utara",
      phone: "+6281234567912",
      businessId: "5",
      image: null,
      createdAt: new Date(),
      updatedAt: new Date(),
      business: business[4],
    },
    {
      id: "24",
      name: "Epsilon Food Court Mal Taman Anggrek",
      address: "Mal Taman Anggrek, Jl. Taman Anggrek No. 3, Jakarta Barat",
      phone: "+6281234567913",
      businessId: "5",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxpVkU6L_4FB2LGueJ_QPdT_vuibIvbTiPDQ&s",
      createdAt: new Date(),
      updatedAt: new Date(),
      business: business[4],
    },

    // Additional outlets for variety
    {
      id: "25",
      name: "Acme Pluit Junction",
      address: "Pluit Junction Mall, Jl. Pluit Selatan No. 1, Jakarta Utara",
      phone: "+6281234567914",
      businessId: "1",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUD3RvDNL0Idc4lwUBfhbE7nFpjRwCJqD3HQ&s",
      createdAt: new Date(),
      updatedAt: new Date(),
      business: business[0],
    },
    {
      id: "26",
      name: "Beta Mart Fatmawati",
      address: "Jl. Fatmawati No. 123, Jakarta Selatan",
      phone: "+6281234567915",
      businessId: "2",
      image: null,
      createdAt: new Date(),
      updatedAt: new Date(),
      business: business[1],
    },
    {
      id: "27",
      name: "Gamma Electronics Karawaci",
      address: "Supermall Karawaci, Jl. Boulevard Diponegoro No. 105, Tangerang",
      phone: "+6281234567916",
      businessId: "3",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSz9uJiPPaqjtr6F0-R_Nbsd19TyBWiRI9SuA&s",
      createdAt: new Date(),
      updatedAt: new Date(),
      business: business[2],
    },
    {
      id: "28",
      name: "Delta Fashion Summarecon",
      address: "Summarecon Mall Serpong, Jl. Boulevard Gading Serpong, Tangerang",
      phone: "+6281234567917",
      businessId: "4",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxpVkU6L_4FB2LGueJ_QPdT_vuibIvbTiPDQ&s",
      createdAt: new Date(),
      updatedAt: new Date(),
      business: business[3],
    },
    {
      id: "29",
      name: "Epsilon Food Court Depok Town Square",
      address: "Depok Town Square, Jl. Margonda Raya No. 1, Depok",
      phone: "+6281234567918",
      businessId: "5",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUD3RvDNL0Idc4lwUBfhbE7nFpjRwCJqD3HQ&s",
      createdAt: new Date(),
      updatedAt: new Date(),
      business: business[4],
    },
    {
      id: "30",
      name: "Acme Bekasi Cyber Park",
      address: "Bekasi Cyber Park, Jl. KH Noer Ali No. 1, Bekasi",
      phone: "+6281234567919",
      businessId: "1",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSz9uJiPPaqjtr6F0-R_Nbsd19TyBWiRI9SuA&s",
      createdAt: new Date(),
      updatedAt: new Date(),
      business: business[0],
    }
  ];

  // Apply search filter
  let filteredOutlets = outlets;
  if (search) {
    const searchLower = search.toLowerCase();
    filteredOutlets = outlets.filter(outlet => 
      outlet.name.toLowerCase().includes(searchLower) ||
      outlet.address.toLowerCase().includes(searchLower) ||
      outlet.business.name.toLowerCase().includes(searchLower) ||
      outlet.business.description.toLowerCase().includes(searchLower)
    );
  }

  // Apply limit
  const result = limit ? filteredOutlets.slice(0, limit) : filteredOutlets;

  return {
    success: true,
    data: result,
    meta: {
      total: filteredOutlets.length,
      totalAll: outlets.length,
      limit: limit || null,
      search: search || null
    }
  };
});
