// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBanner = "Banner"

// Banner mapped from table <Banner>
type Banner struct {
	ID         string    `gorm:"column:id;primaryKey" json:"id"`
	Title      string    `gorm:"column:title;not null" json:"title"`
	Subtitle   string    `gorm:"column:subtitle" json:"subtitle"`
	ImageURL   string    `gorm:"column:imageUrl;not null" json:"imageUrl"`
	CtaType    string    `gorm:"column:ctaType;not null;default:url" json:"ctaType"`
	CtaPayload string    `gorm:"column:ctaPayload" json:"ctaPayload"`
	SortOrder  int32     `gorm:"column:sortOrder;not null" json:"sortOrder"`
	IsActive   bool      `gorm:"column:isActive;not null;default:true" json:"isActive"`
	BusinessID string    `gorm:"column:businessId" json:"businessId"`
	CreatedAt  time.Time `gorm:"column:createdAt;not null;default:CURRENT_TIMESTAMP" json:"createdAt"`
	UpdatedAt  time.Time `gorm:"column:updatedAt;not null" json:"updatedAt"`
}

// TableName Banner's table name
func (*Banner) TableName() string {
	return TableNameBanner
}
