// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBookingSlot = "BookingSlot"

// BookingSlot mapped from table <BookingSlot>
type BookingSlot struct {
	ID               string    `gorm:"column:id;primaryKey" json:"id"`
	Date             time.Time `gorm:"column:date;not null" json:"date"`
	StartTime        time.Time `gorm:"column:startTime;not null" json:"startTime"`
	EndTime          time.Time `gorm:"column:endTime;not null" json:"endTime"`
	Status           string    `gorm:"column:status;not null;default:AVAILABLE" json:"status"`
	ProductServiceID string    `gorm:"column:productServiceId;not null" json:"productServiceId"`
	OrderItemID      string    `gorm:"column:orderItemId" json:"orderItemId"`
	CreatedAt        time.Time `gorm:"column:createdAt;not null;default:CURRENT_TIMESTAMP" json:"createdAt"`
	UpdatedAt        time.Time `gorm:"column:updatedAt;not null" json:"updatedAt"`
}

// TableName BookingSlot's table name
func (*BookingSlot) TableName() string {
	return TableNameBookingSlot
}
