// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBusiness = "Business"

// Business mapped from table <Business>
type Business struct {
	ID                    string    `gorm:"column:id;primaryKey" json:"id"`
	Name                  string    `gorm:"column:name;not null" json:"name"`
	Description           string    `gorm:"column:description" json:"description"`
	CreatedAt             time.Time `gorm:"column:createdAt;not null;default:CURRENT_TIMESTAMP" json:"createdAt"`
	UpdatedAt             time.Time `gorm:"column:updatedAt;not null" json:"updatedAt"`
	BankName              string    `gorm:"column:bankName" json:"bankName"`
	BankAccount           string    `gorm:"column:bankAccount" json:"bankAccount"`
	AccountHolder         string    `gorm:"column:accountHolder" json:"accountHolder"`
	SubscriptionStatus    string    `gorm:"column:subscriptionStatus;not null;default:ACTIVE" json:"subscriptionStatus"`
	SubscriptionStartDate time.Time `gorm:"column:subscriptionStartDate;not null;default:CURRENT_TIMESTAMP" json:"subscriptionStartDate"`
	SubscriptionEndDate   time.Time `gorm:"column:subscriptionEndDate" json:"subscriptionEndDate"`
	SubscriptionPlan      string    `gorm:"column:subscriptionPlan;not null;default:BASIC" json:"subscriptionPlan"`
	OwnerID               string    `gorm:"column:ownerId;not null" json:"ownerId"`
	CurrentSubscriptionID string    `gorm:"column:currentSubscriptionId" json:"currentSubscriptionId"`
}

// TableName Business's table name
func (*Business) TableName() string {
	return TableNameBusiness
}
