// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBusinessSubscription = "BusinessSubscription"

// BusinessSubscription mapped from table <BusinessSubscription>
type BusinessSubscription struct {
	ID         string    `gorm:"column:id;primaryKey" json:"id"`
	Status     string    `gorm:"column:status;not null" json:"status"`
	StartDate  time.Time `gorm:"column:startDate;not null;default:CURRENT_TIMESTAMP" json:"startDate"`
	EndDate    time.Time `gorm:"column:endDate;not null" json:"endDate"`
	BusinessID string    `gorm:"column:businessId;not null" json:"businessId"`
	PlanID     string    `gorm:"column:planId;not null" json:"planId"`
	AutoRenew  bool      `gorm:"column:autoRenew;not null;default:true" json:"autoRenew"`
	CreatedAt  time.Time `gorm:"column:createdAt;not null;default:CURRENT_TIMESTAMP" json:"createdAt"`
	UpdatedAt  time.Time `gorm:"column:updatedAt;not null" json:"updatedAt"`
}

// TableName BusinessSubscription's table name
func (*BusinessSubscription) TableName() string {
	return TableNameBusinessSubscription
}
