// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameExpense = "expenses"

// Expense mapped from table <expenses>
type Expense struct {
	ID          string    `gorm:"column:id;primaryKey" json:"id"`
	Description string    `gorm:"column:description;not null" json:"description"`
	Amount      float64   `gorm:"column:amount;not null" json:"amount"`
	Date        time.Time `gorm:"column:date;not null" json:"date"`
	CreatedAt   time.Time `gorm:"column:createdAt;not null;default:CURRENT_TIMESTAMP" json:"createdAt"`
	UpdatedAt   time.Time `gorm:"column:updatedAt;not null" json:"updatedAt"`
	OutletID    string    `gorm:"column:outletId;not null" json:"outletId"`
	Cashier     string    `gorm:"column:cashier;not null;default:Owner" json:"cashier"`
	ReceiptURL  string    `gorm:"column:receiptUrl" json:"receiptUrl"`
}

// TableName Expense's table name
func (*Expense) TableName() string {
	return TableNameExpense
}
