// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMembership = "Membership"

// Membership mapped from table <Membership>
type Membership struct {
	ID              string    `gorm:"column:id;primaryKey" json:"id"`
	GuestCustomerID string    `gorm:"column:guestCustomerId;not null" json:"guestCustomerId"`
	OrderID         string    `gorm:"column:orderId;not null" json:"orderId"`
	JoinedAt        time.Time `gorm:"column:joinedAt;not null;default:CURRENT_TIMESTAMP" json:"joinedAt"`
	Point           int32     `gorm:"column:point;not null" json:"point"`
}

// TableName Membership's table name
func (*Membership) TableName() string {
	return TableNameMembership
}
