// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOrderItem = "OrderItem"

// OrderItem mapped from table <OrderItem>
type OrderItem struct {
	ID                 string  `gorm:"column:id;primaryKey" json:"id"`
	Quantity           int32   `gorm:"column:quantity;not null" json:"quantity"`
	PriceAtTimeOfOrder float64 `gorm:"column:priceAtTimeOfOrder;not null" json:"priceAtTimeOfOrder"`
	OrderID            string  `gorm:"column:orderId;not null" json:"orderId"`
	ProductID          string  `gorm:"column:productId;not null" json:"productId"`
}

// TableName OrderItem's table name
func (*OrderItem) TableName() string {
	return TableNameOrderItem
}
