// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOrder = "Order"

// Order mapped from table <Order>
type Order struct {
	ID                       string    `gorm:"column:id;primaryKey" json:"id"`
	TotalAmount              float64   `gorm:"column:totalAmount;not null" json:"totalAmount"`
	BookingDate              time.Time `gorm:"column:bookingDate" json:"bookingDate"`
	CustomerType             string    `gorm:"column:customerType;not null;default:GUEST" json:"customerType"`
	PaymentStatus            string    `gorm:"column:paymentStatus;not null;default:PENDING" json:"paymentStatus"`
	PaymentReminderSent      bool      `gorm:"column:paymentReminderSent;not null" json:"paymentReminderSent"`
	OrderStatus              string    `gorm:"column:orderStatus;not null;default:AWAITING_PAYMENT" json:"orderStatus"`
	MidtransTransactionToken string    `gorm:"column:midtransTransactionToken" json:"midtransTransactionToken"`
	MidtransRedirectURL      string    `gorm:"column:midtransRedirectUrl" json:"midtransRedirectUrl"`
	MidtransFee              float64   `gorm:"column:midtransFee;not null" json:"midtransFee"`
	AppFee                   float64   `gorm:"column:appFee;not null" json:"appFee"`
	GuestCustomerID          string    `gorm:"column:guestCustomerId;not null" json:"guestCustomerId"`
	OutletID                 string    `gorm:"column:outletId;not null" json:"outletId"`
	HandledByStaffID         string    `gorm:"column:handledByStaffId" json:"handledByStaffId"`
	CreatedAt                time.Time `gorm:"column:createdAt;not null;default:CURRENT_TIMESTAMP" json:"createdAt"`
	UpdatedAt                time.Time `gorm:"column:updatedAt;not null" json:"updatedAt"`
	CancellationReason       string    `gorm:"column:cancellationReason" json:"cancellationReason"`
}

// TableName Order's table name
func (*Order) TableName() string {
	return TableNameOrder
}
