// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOutletOperatingHour = "OutletOperatingHours"

// OutletOperatingHour mapped from table <OutletOperatingHours>
type OutletOperatingHour struct {
	ID        string    `gorm:"column:id;primaryKey" json:"id"`
	DayOfWeek int32     `gorm:"column:dayOfWeek;not null" json:"dayOfWeek"`
	OpenTime  time.Time `gorm:"column:openTime;not null" json:"openTime"`
	CloseTime time.Time `gorm:"column:closeTime;not null" json:"closeTime"`
	IsOpen    bool      `gorm:"column:isOpen;not null;default:true" json:"isOpen"`
	OutletID  string    `gorm:"column:outletId;not null" json:"outletId"`
	CreatedAt time.Time `gorm:"column:createdAt;not null;default:CURRENT_TIMESTAMP" json:"createdAt"`
	UpdatedAt time.Time `gorm:"column:updatedAt;not null" json:"updatedAt"`
}

// TableName OutletOperatingHour's table name
func (*OutletOperatingHour) TableName() string {
	return TableNameOutletOperatingHour
}
