// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOutlet = "Outlet"

// Outlet mapped from table <Outlet>
type Outlet struct {
	ID                  string    `gorm:"column:id;primaryKey" json:"id"`
	Name                string    `gorm:"column:name;not null" json:"name"`
	Description         string    `gorm:"column:description" json:"description"`
	Address             string    `gorm:"column:address" json:"address"`
	Phone               string    `gorm:"column:phone" json:"phone"`
	CreatedAt           time.Time `gorm:"column:createdAt;not null;default:CURRENT_TIMESTAMP" json:"createdAt"`
	Image               string    `gorm:"column:image;default:/defaults/default-outlet-image.webp" json:"image"`
	UpdatedAt           time.Time `gorm:"column:updatedAt;not null" json:"updatedAt"`
	Latitude            float64   `gorm:"column:latitude" json:"latitude"`
	Longitude           float64   `gorm:"column:longitude" json:"longitude"`
	IsOpen              bool      `gorm:"column:isOpen;not null" json:"isOpen"`
	BusinessID          string    `gorm:"column:businessId;not null" json:"businessId"`
	ManualBankName      string    `gorm:"column:manualBankName" json:"manualBankName"`
	ManualBankAccount   string    `gorm:"column:manualBankAccount" json:"manualBankAccount"`
	ManualAccountHolder string    `gorm:"column:manualAccountHolder" json:"manualAccountHolder"`
	ManualPaymentNote   string    `gorm:"column:manualPaymentNote" json:"manualPaymentNote"`
	ManualQrImageURL    string    `gorm:"column:manualQrImageUrl" json:"manualQrImageUrl"`
	Slug                string    `gorm:"column:slug" json:"slug"`
	Email               string    `gorm:"column:email" json:"email"`
}

// TableName Outlet's table name
func (*Outlet) TableName() string {
	return TableNameOutlet
}
