// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProductGood = "ProductGoods"

// ProductGood mapped from table <ProductGoods>
type ProductGood struct {
	ID           string    `gorm:"column:id;primaryKey" json:"id"`
	ProductID    string    `gorm:"column:productId;not null" json:"productId"`
	CurrentStock int32     `gorm:"column:currentStock;not null" json:"currentStock"`
	MinStock     int32     `gorm:"column:minStock" json:"minStock"`
	Unit         string    `gorm:"column:unit;not null" json:"unit"`
	AverageHpp   float64   `gorm:"column:averageHpp;not null" json:"averageHpp"`
	SellingPrice float64   `gorm:"column:sellingPrice;not null" json:"sellingPrice"`
	CreatedAt    time.Time `gorm:"column:createdAt;not null;default:CURRENT_TIMESTAMP" json:"createdAt"`
	UpdatedAt    time.Time `gorm:"column:updatedAt;not null" json:"updatedAt"`
	MaxStock     int32     `gorm:"column:maxStock" json:"maxStock"`
}

// TableName ProductGood's table name
func (*ProductGood) TableName() string {
	return TableNameProductGood
}
