// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProductMedium = "ProductMedia"

// ProductMedium mapped from table <ProductMedia>
type ProductMedium struct {
	ID           string    `gorm:"column:id;primaryKey" json:"id"`
	ProductID    string    `gorm:"column:productId;not null" json:"productId"`
	URL          string    `gorm:"column:url;not null" json:"url"`
	Type         string    `gorm:"column:type;not null;default:IMAGE" json:"type"`
	Source       string    `gorm:"column:source;not null;default:UPLOAD" json:"source"`
	Alt          string    `gorm:"column:alt" json:"alt"`
	Order_       int32     `gorm:"column:order;not null" json:"order"`
	ThumbnailURL string    `gorm:"column:thumbnailUrl" json:"thumbnailUrl"`
	CreatedAt    time.Time `gorm:"column:createdAt;not null;default:CURRENT_TIMESTAMP" json:"createdAt"`
	UpdatedAt    time.Time `gorm:"column:updatedAt;not null" json:"updatedAt"`
}

// TableName ProductMedium's table name
func (*ProductMedium) TableName() string {
	return TableNameProductMedium
}
