// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProduct = "Product"

// Product mapped from table <Product>
type Product struct {
	ID          string    `gorm:"column:id;primaryKey" json:"id"`
	Name        string    `gorm:"column:name;not null" json:"name"`
	Description string    `gorm:"column:description" json:"description"`
	Type        string    `gorm:"column:type;not null" json:"type"`
	Status      string    `gorm:"column:status;not null;default:ACTIVE" json:"status"`
	OutletID    string    `gorm:"column:outletId;not null" json:"outletId"`
	Image       string    `gorm:"column:image;default:/defaults/default-product-image.png" json:"image"`
	CreatedAt   time.Time `gorm:"column:createdAt;not null;default:CURRENT_TIMESTAMP" json:"createdAt"`
	UpdatedAt   time.Time `gorm:"column:updatedAt;not null" json:"updatedAt"`
}

// TableName Product's table name
func (*Product) TableName() string {
	return TableNameProduct
}
