// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProductService = "ProductService"

// ProductService mapped from table <ProductService>
type ProductService struct {
	ID                 string    `gorm:"column:id;primaryKey" json:"id"`
	ProductID          string    `gorm:"column:productId;not null" json:"productId"`
	DurationMinutes    int32     `gorm:"column:durationMinutes;not null" json:"durationMinutes"`
	SellingPrice       float64   `gorm:"column:sellingPrice;not null" json:"sellingPrice"`
	ProviderName       string    `gorm:"column:providerName;not null" json:"providerName"`
	ProviderPhone      string    `gorm:"column:providerPhone" json:"providerPhone"`
	ProviderEmail      string    `gorm:"column:providerEmail" json:"providerEmail"`
	CommissionType     string    `gorm:"column:commissionType;not null;default:PERCENTAGE" json:"commissionType"`
	CommissionValue    float64   `gorm:"column:commissionValue;not null" json:"commissionValue"`
	MaxParallel        int32     `gorm:"column:maxParallel;not null;default:1" json:"maxParallel"`
	CreatedAt          time.Time `gorm:"column:createdAt;not null;default:CURRENT_TIMESTAMP" json:"createdAt"`
	UpdatedAt          time.Time `gorm:"column:updatedAt;not null" json:"updatedAt"`
	BookingInWorkHours bool      `gorm:"column:bookingInWorkHours;not null;default:true" json:"bookingInWorkHours"`
	FridayClose        time.Time `gorm:"column:fridayClose" json:"fridayClose"`
	FridayOpen         time.Time `gorm:"column:fridayOpen" json:"fridayOpen"`
	MondayClose        time.Time `gorm:"column:mondayClose" json:"mondayClose"`
	MondayOpen         time.Time `gorm:"column:mondayOpen" json:"mondayOpen"`
	SaturdayClose      time.Time `gorm:"column:saturdayClose" json:"saturdayClose"`
	SaturdayOpen       time.Time `gorm:"column:saturdayOpen" json:"saturdayOpen"`
	SundayClose        time.Time `gorm:"column:sundayClose" json:"sundayClose"`
	SundayOpen         time.Time `gorm:"column:sundayOpen" json:"sundayOpen"`
	ThursdayClose      time.Time `gorm:"column:thursdayClose" json:"thursdayClose"`
	ThursdayOpen       time.Time `gorm:"column:thursdayOpen" json:"thursdayOpen"`
	TuesdayClose       time.Time `gorm:"column:tuesdayClose" json:"tuesdayClose"`
	TuesdayOpen        time.Time `gorm:"column:tuesdayOpen" json:"tuesdayOpen"`
	WednesdayClose     time.Time `gorm:"column:wednesdayClose" json:"wednesdayClose"`
	WednesdayOpen      time.Time `gorm:"column:wednesdayOpen" json:"wednesdayOpen"`
}

// TableName ProductService's table name
func (*ProductService) TableName() string {
	return TableNameProductService
}
