// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProductTicket = "ProductTicket"

// ProductTicket mapped from table <ProductTicket>
type ProductTicket struct {
	ID            string    `gorm:"column:id;primaryKey" json:"id"`
	ProductID     string    `gorm:"column:productId;not null" json:"productId"`
	SellingPrice  float64   `gorm:"column:sellingPrice;not null" json:"sellingPrice"`
	EventDate     time.Time `gorm:"column:eventDate;not null" json:"eventDate"`
	EventEndDate  time.Time `gorm:"column:eventEndDate" json:"eventEndDate"`
	Venue         string    `gorm:"column:venue;not null" json:"venue"`
	VenueAddress  string    `gorm:"column:venueAddress" json:"venueAddress"`
	MapURL        string    `gorm:"column:mapUrl" json:"mapUrl"`
	TotalQuota    int32     `gorm:"column:totalQuota;not null" json:"totalQuota"`
	SoldCount     int32     `gorm:"column:soldCount;not null" json:"soldCount"`
	MaxPerOrder   int32     `gorm:"column:maxPerOrder;not null;default:5" json:"maxPerOrder"`
	SaleStartDate time.Time `gorm:"column:saleStartDate" json:"saleStartDate"`
	SaleEndDate   time.Time `gorm:"column:saleEndDate" json:"saleEndDate"`
	Terms         string    `gorm:"column:terms" json:"terms"`
	CreatedAt     time.Time `gorm:"column:createdAt;not null;default:CURRENT_TIMESTAMP" json:"createdAt"`
	UpdatedAt     time.Time `gorm:"column:updatedAt;not null" json:"updatedAt"`
}

// TableName ProductTicket's table name
func (*ProductTicket) TableName() string {
	return TableNameProductTicket
}
