// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameReceiptSetting = "receiptSetting"

// ReceiptSetting mapped from table <receiptSetting>
type ReceiptSetting struct {
	ID          string `gorm:"column:id;primaryKey" json:"id"`
	OutletID    string `gorm:"column:outletId;not null" json:"outletId"`
	PhotoString string `gorm:"column:photoString" json:"photoString"`
	ShowLogo    bool   `gorm:"column:showLogo;not null" json:"showLogo"`
	PrintHeight string `gorm:"column:printHeight;not null;default:105" json:"printHeight"`
	PrintWidth  string `gorm:"column:printWidth;not null;default:80" json:"printWidth"`
}

// TableName ReceiptSetting's table name
func (*ReceiptSetting) TableName() string {
	return TableNameReceiptSetting
}
