// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameStaff = "Staff"

// Staff mapped from table <Staff>
type Staff struct {
	ID        string    `gorm:"column:id;primaryKey" json:"id"`
	Name      string    `gorm:"column:name;not null" json:"name"`
	Phone     string    `gorm:"column:phone" json:"phone"`
	Email     string    `gorm:"column:email" json:"email"`
	Password  string    `gorm:"column:password;not null" json:"password"`
	Status    string    `gorm:"column:status;not null;default:ACTIVE" json:"status"`
	OutletID  string    `gorm:"column:outletId;not null" json:"outletId"`
	CreatedAt time.Time `gorm:"column:createdAt;not null;default:CURRENT_TIMESTAMP" json:"createdAt"`
	UpdatedAt time.Time `gorm:"column:updatedAt;not null" json:"updatedAt"`
}

// TableName Staff's table name
func (*Staff) TableName() string {
	return TableNameStaff
}
