// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameStockLog = "StockLog"

// StockLog mapped from table <StockLog>
type StockLog struct {
	ID             string    `gorm:"column:id;primaryKey" json:"id"`
	Type           string    `gorm:"column:type;not null" json:"type"`
	Quantity       int32     `gorm:"column:quantity;not null" json:"quantity"`
	HppPerUnit     float64   `gorm:"column:hppPerUnit" json:"hppPerUnit"`
	ReferenceType  string    `gorm:"column:referenceType" json:"referenceType"`
	ReferenceID    string    `gorm:"column:referenceId" json:"referenceId"`
	Notes          string    `gorm:"column:notes" json:"notes"`
	ProductGoodsID string    `gorm:"column:productGoodsId;not null" json:"productGoodsId"`
	CreatedAt      time.Time `gorm:"column:createdAt;not null;default:CURRENT_TIMESTAMP" json:"createdAt"`
	Faktur         string    `gorm:"column:faktur" json:"faktur"`
}

// TableName StockLog's table name
func (*StockLog) TableName() string {
	return TableNameStockLog
}
