// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSubscriptionPlan = "SubscriptionPlan"

// SubscriptionPlan mapped from table <SubscriptionPlan>
type SubscriptionPlan struct {
	ID           string    `gorm:"column:id;primaryKey" json:"id"`
	Name         string    `gorm:"column:name;not null" json:"name"`
	Code         string    `gorm:"column:code;not null" json:"code"`
	Price        float64   `gorm:"column:price;not null" json:"price"`
	DurationDays int32     `gorm:"column:durationDays;not null" json:"durationDays"`
	Features     string    `gorm:"column:features;not null" json:"features"`
	IsActive     bool      `gorm:"column:isActive;not null;default:true" json:"isActive"`
	IsPopular    bool      `gorm:"column:isPopular;not null" json:"isPopular"`
	CreatedAt    time.Time `gorm:"column:createdAt;not null;default:CURRENT_TIMESTAMP" json:"createdAt"`
	UpdatedAt    time.Time `gorm:"column:updatedAt;not null" json:"updatedAt"`
	Promo        string    `gorm:"column:promo" json:"promo"`
}

// TableName SubscriptionPlan's table name
func (*SubscriptionPlan) TableName() string {
	return TableNameSubscriptionPlan
}
