// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSubscriptionInvoice = "SubscriptionInvoice"

// SubscriptionInvoice mapped from table <SubscriptionInvoice>
type SubscriptionInvoice struct {
	ID              string    `gorm:"column:id;primaryKey" json:"id"`
	InvoiceNumber   string    `gorm:"column:invoiceNumber;not null" json:"invoiceNumber"`
	Amount          float64   `gorm:"column:amount;not null" json:"amount"`
	Status          string    `gorm:"column:status;not null" json:"status"`
	PaymentURL      string    `gorm:"column:paymentUrl" json:"paymentUrl"`
	ExternalID      string    `gorm:"column:externalId" json:"externalId"`
	ProofImage      string    `gorm:"column:proofImage" json:"proofImage"`
	VerifiedAt      time.Time `gorm:"column:verifiedAt" json:"verifiedAt"`
	RejectionReason string    `gorm:"column:rejectionReason" json:"rejectionReason"`
	PaidAt          time.Time `gorm:"column:paidAt" json:"paidAt"`
	BusinessID      string    `gorm:"column:businessId" json:"businessId"`
	SubscriptionID  string    `gorm:"column:subscriptionId" json:"subscriptionId"`
	CreatedAt       time.Time `gorm:"column:createdAt;not null;default:CURRENT_TIMESTAMP" json:"createdAt"`
	UpdatedAt       time.Time `gorm:"column:updatedAt;not null" json:"updatedAt"`
	ProofUploadedAt time.Time `gorm:"column:proofUploadedAt" json:"proofUploadedAt"`
}

// TableName SubscriptionInvoice's table name
func (*SubscriptionInvoice) TableName() string {
	return TableNameSubscriptionInvoice
}
