// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTicketCode = "TicketCode"

// TicketCode mapped from table <TicketCode>
type TicketCode struct {
	ID           string    `gorm:"column:id;primaryKey" json:"id"`
	Code         string    `gorm:"column:code;not null" json:"code"`
	Status       string    `gorm:"column:status;not null;default:VALID" json:"status"`
	OrderItemID  string    `gorm:"column:orderItemId;not null" json:"orderItemId"`
	RedeemedAt   time.Time `gorm:"column:redeemedAt" json:"redeemedAt"`
	RedeemedByID string    `gorm:"column:redeemedById" json:"redeemedById"`
	CreatedAt    time.Time `gorm:"column:createdAt;not null;default:CURRENT_TIMESTAMP" json:"createdAt"`
	UpdatedAt    time.Time `gorm:"column:updatedAt;not null" json:"updatedAt"`
}

// TableName TicketCode's table name
func (*TicketCode) TableName() string {
	return TableNameTicketCode
}
