// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTransactionRecord = "Transaction"

// TransactionRecord mapped from table <Transaction>
type TransactionRecord struct {
	ID              string    `gorm:"column:id;primaryKey" json:"id"`
	Amount          float64   `gorm:"column:amount;not null" json:"amount"`
	PaymentMethod   string    `gorm:"column:paymentMethod" json:"paymentMethod"`
	Status          string    `gorm:"column:status;not null;default:PENDING" json:"status"`
	IsManual        bool      `gorm:"column:isManual;not null" json:"isManual"`
	ManualMethod    string    `gorm:"column:manualMethod" json:"manualMethod"`
	PaymentProofURL string    `gorm:"column:paymentProofUrl" json:"paymentProofUrl"`
	ProofUploadedAt time.Time `gorm:"column:proofUploadedAt" json:"proofUploadedAt"`
	VerifiedAt      time.Time `gorm:"column:verifiedAt" json:"verifiedAt"`
	VerifiedByID    string    `gorm:"column:verifiedById" json:"verifiedById"`
	RejectionNote   string    `gorm:"column:rejectionNote" json:"rejectionNote"`
	RawMidtrans     string    `gorm:"column:rawMidtrans" json:"rawMidtrans"`
	ExternalID      string    `gorm:"column:externalId" json:"externalId"`
	PaymentURL      string    `gorm:"column:paymentUrl" json:"paymentUrl"`
	ExpiresAt       time.Time `gorm:"column:expiresAt" json:"expiresAt"`
	OrderID         string    `gorm:"column:orderId;not null" json:"orderId"`
	CreatedAt       time.Time `gorm:"column:createdAt;not null;default:CURRENT_TIMESTAMP" json:"createdAt"`
}

// TableName TransactionRecord's table name
func (*TransactionRecord) TableName() string {
	return TableNameTransactionRecord
}
