// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "User"

// User mapped from table <User>
type User struct {
	ID                      string    `gorm:"column:id;primaryKey" json:"id"`
	Email                   string    `gorm:"column:email;not null" json:"email"`
	Name                    string    `gorm:"column:name;not null" json:"name"`
	Avatar                  string    `gorm:"column:avatar" json:"avatar"`
	Password                string    `gorm:"column:password;not null" json:"password"`
	Role                    string    `gorm:"column:role;not null;default:OWNER" json:"role"`
	IsVerified              bool      `gorm:"column:isVerified;not null" json:"isVerified"`
	VerificationCode        string    `gorm:"column:verificationCode" json:"verificationCode"`
	VerificationCodeExpires time.Time `gorm:"column:verificationCodeExpires" json:"verificationCodeExpires"`
	Phone                   string    `gorm:"column:phone" json:"phone"`
	GoogleID                string    `gorm:"column:googleId" json:"googleId"`
	Provider                string    `gorm:"column:provider;default:local" json:"provider"`
	CreatedAt               time.Time `gorm:"column:createdAt;not null;default:CURRENT_TIMESTAMP" json:"createdAt"`
	UpdatedAt               time.Time `gorm:"column:updatedAt;not null" json:"updatedAt"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
