-- AlterTable
ALTER TABLE "Order" ADD COLUMN     "bookingFee" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "chargedTo" "FeeBearer" NOT NULL DEFAULT 'CUSTOMER',
ADD COLUMN     "platformFee" DOUBLE PRECISION NOT NULL DEFAULT 0;
