export const Messages = {
    SUCCESS: 'Success',
    CREATED: 'Created successfully',
    BAD_REQUEST: 'Bad request',
    UNAUTHORIZED: 'Unauthorized',
    FORBIDDEN: 'Forbidden',
    NOT_FOUND: 'Not found',
    CONFLICT: 'Conflict occurred',
    INTERNAL_ERROR: 'Internal server error',
    INVALID_CREDENTIALS: 'Email or password is incorrect',
    VALIDATION_FAILED: 'Validation failed',
    NOT_LOGGED_IN: 'Anda belum login, silakan login terlebih dahulu',
    INVALID_TOKEN: 'Token tidak valid atau kadaluarsa',
    USER_NOT_FOUND: 'Pengguna yang terkait dengan token ini tidak ada lagi',
};
