name: "Deploy Backend"

on:
  push:
    branches:
      - develop
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'
      - 'docker-compose.dev.yml'
      - 'docker-compose.prod.yml'

jobs:
  deploy_dev:
    name: Build & Deploy Dev
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER }}/project-backend:development
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            SMTP_HOST=${{ vars.SMTP_HOST }}
            SMTP_PORT=${{ vars.SMTP_PORT }}
            SMTP_USER=${{ vars.SMTP_USER }}
            SMTP_PASS=${{ vars.SMTP_PASS }}
            SMTP_FROM=${{ vars.SMTP_FROM }}
            NODE_ENV=development
            COOKIES_DOMAIN=.bossapp.id
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            CLIENT_URL=${{ vars.CLIENT_URL }}

      - name: Create project directory on VPS if it does not exist
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USER }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            mkdir -p ~/projects/boss-project/dev

      - name: Copy docker-compose file to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USER }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          source: "./docker-compose.dev.yml"
          target: "~/projects/boss-project/dev"

      - name: Deploy to Dev
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USER }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            cd ~/projects/boss-project/dev
            echo "Pulling backend image..."
            docker compose -f docker-compose.dev.yml pull backend
            echo "Starting backend service..."
            docker compose -f docker-compose.dev.yml up -d --no-deps --build backend
            echo "Backend deployed successfully"

      - name: Send Telegram Notification (Deploy)
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          message: |
            🚀 **Deploy Status Backend (Dev)**
            **Status:** ${{ job.status }}
            **Triggered by:** ${{ github.actor }}
            **Commit:** ${{ github.sha }}
            [View Commit](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})

  deploy_prod:
    name: Build & Deploy Prod
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER }}/project-backend:production
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            SMTP_HOST=${{ vars.SMPT_HOST }}
            SMTP_PORT=${{ vars.SMTP_PORT }}
            SMTP_USER=${{ vars.SMTP_USER}}
            SMTP_PASS=${{ vars.SMTP_PASS }}
            SMTP_FROM=${{ vars.SMTP_FROM }}
            NODE_ENV=production
            COOKIES_DOMAIN=.bossapp.id
            DATABASE_URL=${{ vars.DATABASE_URL }}
            CLIENT_URL=${{ vars.CLIENT_URL }}

      - name: Create project directory on VPS if it does not exist
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_VPS_HOST }}
          username: ${{ secrets.PROD_VPS_SSH_USER }}
          key: ${{ secrets.PROD_VPS_SSH_PRIVATE_KEY }}
          script: |
            mkdir -p ~/projects/boss-project/prod

      - name: Copy docker-compose file to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PROD_VPS_HOST }}
          username: ${{ secrets.PROD_VPS_SSH_USER }}
          key: ${{ secrets.PROD_VPS_SSH_PRIVATE_KEY }}
          source: "./docker-compose.prod.yml"
          target: "~/projects/boss-project/prod"

      - name: Deploy to Prod
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_VPS_HOST }}
          username: ${{ secrets.PROD_VPS_SSH_USER }}
          key: ${{ secrets.PROD_VPS_SSH_PRIVATE_KEY }}
          script: |
            cd ~/projects/boss-project/prod
            echo "Pulling latest backend image..."
            docker compose -f docker-compose.prod.yml pull backend
            echo "Starting backend service..."
            docker compose -f docker-compose.prod.yml up -d --no-deps backend
            echo "Backend deployed successfully."
            docker image prune -af || true

      - name: Send Telegram Notification (Deploy)
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          message: |
            🚀 **Deploy Status Backend (Prod)**
            **Status:** ${{ job.status }}
            **Triggered by:** ${{ github.actor }}
            **Commit:** ${{ github.sha }}
            [View Commit](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})
