// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend_go/model"
)

func newBookingSlot(db *gorm.DB, opts ...gen.DOOption) bookingSlot {
	_bookingSlot := bookingSlot{}

	_bookingSlot.bookingSlotDo.UseDB(db, opts...)
	_bookingSlot.bookingSlotDo.UseModel(&model.BookingSlot{})

	tableName := _bookingSlot.bookingSlotDo.TableName()
	_bookingSlot.ALL = field.NewAsterisk(tableName)
	_bookingSlot.ID = field.NewString(tableName, "id")
	_bookingSlot.Date = field.NewTime(tableName, "date")
	_bookingSlot.StartTime = field.NewTime(tableName, "startTime")
	_bookingSlot.EndTime = field.NewTime(tableName, "endTime")
	_bookingSlot.Status = field.NewString(tableName, "status")
	_bookingSlot.ProductServiceID = field.NewString(tableName, "productServiceId")
	_bookingSlot.OrderItemID = field.NewString(tableName, "orderItemId")
	_bookingSlot.CreatedAt = field.NewTime(tableName, "createdAt")
	_bookingSlot.UpdatedAt = field.NewTime(tableName, "updatedAt")

	_bookingSlot.fillFieldMap()

	return _bookingSlot
}

type bookingSlot struct {
	bookingSlotDo

	ALL              field.Asterisk
	ID               field.String
	Date             field.Time
	StartTime        field.Time
	EndTime          field.Time
	Status           field.String
	ProductServiceID field.String
	OrderItemID      field.String
	CreatedAt        field.Time
	UpdatedAt        field.Time

	fieldMap map[string]field.Expr
}

func (b bookingSlot) Table(newTableName string) *bookingSlot {
	b.bookingSlotDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b bookingSlot) As(alias string) *bookingSlot {
	b.bookingSlotDo.DO = *(b.bookingSlotDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *bookingSlot) updateTableName(table string) *bookingSlot {
	b.ALL = field.NewAsterisk(table)
	b.ID = field.NewString(table, "id")
	b.Date = field.NewTime(table, "date")
	b.StartTime = field.NewTime(table, "startTime")
	b.EndTime = field.NewTime(table, "endTime")
	b.Status = field.NewString(table, "status")
	b.ProductServiceID = field.NewString(table, "productServiceId")
	b.OrderItemID = field.NewString(table, "orderItemId")
	b.CreatedAt = field.NewTime(table, "createdAt")
	b.UpdatedAt = field.NewTime(table, "updatedAt")

	b.fillFieldMap()

	return b
}

func (b *bookingSlot) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *bookingSlot) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 9)
	b.fieldMap["id"] = b.ID
	b.fieldMap["date"] = b.Date
	b.fieldMap["startTime"] = b.StartTime
	b.fieldMap["endTime"] = b.EndTime
	b.fieldMap["status"] = b.Status
	b.fieldMap["productServiceId"] = b.ProductServiceID
	b.fieldMap["orderItemId"] = b.OrderItemID
	b.fieldMap["createdAt"] = b.CreatedAt
	b.fieldMap["updatedAt"] = b.UpdatedAt
}

func (b bookingSlot) clone(db *gorm.DB) bookingSlot {
	b.bookingSlotDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b bookingSlot) replaceDB(db *gorm.DB) bookingSlot {
	b.bookingSlotDo.ReplaceDB(db)
	return b
}

type bookingSlotDo struct{ gen.DO }

type IBookingSlotDo interface {
	gen.SubQuery
	Debug() IBookingSlotDo
	WithContext(ctx context.Context) IBookingSlotDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IBookingSlotDo
	WriteDB() IBookingSlotDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IBookingSlotDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IBookingSlotDo
	Not(conds ...gen.Condition) IBookingSlotDo
	Or(conds ...gen.Condition) IBookingSlotDo
	Select(conds ...field.Expr) IBookingSlotDo
	Where(conds ...gen.Condition) IBookingSlotDo
	Order(conds ...field.Expr) IBookingSlotDo
	Distinct(cols ...field.Expr) IBookingSlotDo
	Omit(cols ...field.Expr) IBookingSlotDo
	Join(table schema.Tabler, on ...field.Expr) IBookingSlotDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IBookingSlotDo
	RightJoin(table schema.Tabler, on ...field.Expr) IBookingSlotDo
	Group(cols ...field.Expr) IBookingSlotDo
	Having(conds ...gen.Condition) IBookingSlotDo
	Limit(limit int) IBookingSlotDo
	Offset(offset int) IBookingSlotDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IBookingSlotDo
	Unscoped() IBookingSlotDo
	Create(values ...*model.BookingSlot) error
	CreateInBatches(values []*model.BookingSlot, batchSize int) error
	Save(values ...*model.BookingSlot) error
	First() (*model.BookingSlot, error)
	Take() (*model.BookingSlot, error)
	Last() (*model.BookingSlot, error)
	Find() ([]*model.BookingSlot, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BookingSlot, err error)
	FindInBatches(result *[]*model.BookingSlot, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.BookingSlot) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IBookingSlotDo
	Assign(attrs ...field.AssignExpr) IBookingSlotDo
	Joins(fields ...field.RelationField) IBookingSlotDo
	Preload(fields ...field.RelationField) IBookingSlotDo
	FirstOrInit() (*model.BookingSlot, error)
	FirstOrCreate() (*model.BookingSlot, error)
	FindByPage(offset int, limit int) (result []*model.BookingSlot, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IBookingSlotDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (b bookingSlotDo) Debug() IBookingSlotDo {
	return b.withDO(b.DO.Debug())
}

func (b bookingSlotDo) WithContext(ctx context.Context) IBookingSlotDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b bookingSlotDo) ReadDB() IBookingSlotDo {
	return b.Clauses(dbresolver.Read)
}

func (b bookingSlotDo) WriteDB() IBookingSlotDo {
	return b.Clauses(dbresolver.Write)
}

func (b bookingSlotDo) Session(config *gorm.Session) IBookingSlotDo {
	return b.withDO(b.DO.Session(config))
}

func (b bookingSlotDo) Clauses(conds ...clause.Expression) IBookingSlotDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b bookingSlotDo) Returning(value interface{}, columns ...string) IBookingSlotDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b bookingSlotDo) Not(conds ...gen.Condition) IBookingSlotDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b bookingSlotDo) Or(conds ...gen.Condition) IBookingSlotDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b bookingSlotDo) Select(conds ...field.Expr) IBookingSlotDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b bookingSlotDo) Where(conds ...gen.Condition) IBookingSlotDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b bookingSlotDo) Order(conds ...field.Expr) IBookingSlotDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b bookingSlotDo) Distinct(cols ...field.Expr) IBookingSlotDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b bookingSlotDo) Omit(cols ...field.Expr) IBookingSlotDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b bookingSlotDo) Join(table schema.Tabler, on ...field.Expr) IBookingSlotDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b bookingSlotDo) LeftJoin(table schema.Tabler, on ...field.Expr) IBookingSlotDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b bookingSlotDo) RightJoin(table schema.Tabler, on ...field.Expr) IBookingSlotDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b bookingSlotDo) Group(cols ...field.Expr) IBookingSlotDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b bookingSlotDo) Having(conds ...gen.Condition) IBookingSlotDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b bookingSlotDo) Limit(limit int) IBookingSlotDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b bookingSlotDo) Offset(offset int) IBookingSlotDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b bookingSlotDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IBookingSlotDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b bookingSlotDo) Unscoped() IBookingSlotDo {
	return b.withDO(b.DO.Unscoped())
}

func (b bookingSlotDo) Create(values ...*model.BookingSlot) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b bookingSlotDo) CreateInBatches(values []*model.BookingSlot, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b bookingSlotDo) Save(values ...*model.BookingSlot) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b bookingSlotDo) First() (*model.BookingSlot, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.BookingSlot), nil
	}
}

func (b bookingSlotDo) Take() (*model.BookingSlot, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.BookingSlot), nil
	}
}

func (b bookingSlotDo) Last() (*model.BookingSlot, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.BookingSlot), nil
	}
}

func (b bookingSlotDo) Find() ([]*model.BookingSlot, error) {
	result, err := b.DO.Find()
	return result.([]*model.BookingSlot), err
}

func (b bookingSlotDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BookingSlot, err error) {
	buf := make([]*model.BookingSlot, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b bookingSlotDo) FindInBatches(result *[]*model.BookingSlot, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b bookingSlotDo) Attrs(attrs ...field.AssignExpr) IBookingSlotDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b bookingSlotDo) Assign(attrs ...field.AssignExpr) IBookingSlotDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b bookingSlotDo) Joins(fields ...field.RelationField) IBookingSlotDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b bookingSlotDo) Preload(fields ...field.RelationField) IBookingSlotDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b bookingSlotDo) FirstOrInit() (*model.BookingSlot, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.BookingSlot), nil
	}
}

func (b bookingSlotDo) FirstOrCreate() (*model.BookingSlot, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.BookingSlot), nil
	}
}

func (b bookingSlotDo) FindByPage(offset int, limit int) (result []*model.BookingSlot, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b bookingSlotDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b bookingSlotDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b bookingSlotDo) Delete(models ...*model.BookingSlot) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *bookingSlotDo) withDO(do gen.Dao) *bookingSlotDo {
	b.DO = *do.(*gen.DO)
	return b
}
