// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend_go/model"
)

func newBusiness(db *gorm.DB, opts ...gen.DOOption) business {
	_business := business{}

	_business.businessDo.UseDB(db, opts...)
	_business.businessDo.UseModel(&model.Business{})

	tableName := _business.businessDo.TableName()
	_business.ALL = field.NewAsterisk(tableName)
	_business.ID = field.NewString(tableName, "id")
	_business.Name = field.NewString(tableName, "name")
	_business.Description = field.NewString(tableName, "description")
	_business.CreatedAt = field.NewTime(tableName, "createdAt")
	_business.UpdatedAt = field.NewTime(tableName, "updatedAt")
	_business.BankName = field.NewString(tableName, "bankName")
	_business.BankAccount = field.NewString(tableName, "bankAccount")
	_business.AccountHolder = field.NewString(tableName, "accountHolder")
	_business.SubscriptionStatus = field.NewString(tableName, "subscriptionStatus")
	_business.SubscriptionStartDate = field.NewTime(tableName, "subscriptionStartDate")
	_business.SubscriptionEndDate = field.NewTime(tableName, "subscriptionEndDate")
	_business.SubscriptionPlan = field.NewString(tableName, "subscriptionPlan")
	_business.OwnerID = field.NewString(tableName, "ownerId")
	_business.CurrentSubscriptionID = field.NewString(tableName, "currentSubscriptionId")

	_business.fillFieldMap()

	return _business
}

type business struct {
	businessDo

	ALL                   field.Asterisk
	ID                    field.String
	Name                  field.String
	Description           field.String
	CreatedAt             field.Time
	UpdatedAt             field.Time
	BankName              field.String
	BankAccount           field.String
	AccountHolder         field.String
	SubscriptionStatus    field.String
	SubscriptionStartDate field.Time
	SubscriptionEndDate   field.Time
	SubscriptionPlan      field.String
	OwnerID               field.String
	CurrentSubscriptionID field.String

	fieldMap map[string]field.Expr
}

func (b business) Table(newTableName string) *business {
	b.businessDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b business) As(alias string) *business {
	b.businessDo.DO = *(b.businessDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *business) updateTableName(table string) *business {
	b.ALL = field.NewAsterisk(table)
	b.ID = field.NewString(table, "id")
	b.Name = field.NewString(table, "name")
	b.Description = field.NewString(table, "description")
	b.CreatedAt = field.NewTime(table, "createdAt")
	b.UpdatedAt = field.NewTime(table, "updatedAt")
	b.BankName = field.NewString(table, "bankName")
	b.BankAccount = field.NewString(table, "bankAccount")
	b.AccountHolder = field.NewString(table, "accountHolder")
	b.SubscriptionStatus = field.NewString(table, "subscriptionStatus")
	b.SubscriptionStartDate = field.NewTime(table, "subscriptionStartDate")
	b.SubscriptionEndDate = field.NewTime(table, "subscriptionEndDate")
	b.SubscriptionPlan = field.NewString(table, "subscriptionPlan")
	b.OwnerID = field.NewString(table, "ownerId")
	b.CurrentSubscriptionID = field.NewString(table, "currentSubscriptionId")

	b.fillFieldMap()

	return b
}

func (b *business) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *business) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 14)
	b.fieldMap["id"] = b.ID
	b.fieldMap["name"] = b.Name
	b.fieldMap["description"] = b.Description
	b.fieldMap["createdAt"] = b.CreatedAt
	b.fieldMap["updatedAt"] = b.UpdatedAt
	b.fieldMap["bankName"] = b.BankName
	b.fieldMap["bankAccount"] = b.BankAccount
	b.fieldMap["accountHolder"] = b.AccountHolder
	b.fieldMap["subscriptionStatus"] = b.SubscriptionStatus
	b.fieldMap["subscriptionStartDate"] = b.SubscriptionStartDate
	b.fieldMap["subscriptionEndDate"] = b.SubscriptionEndDate
	b.fieldMap["subscriptionPlan"] = b.SubscriptionPlan
	b.fieldMap["ownerId"] = b.OwnerID
	b.fieldMap["currentSubscriptionId"] = b.CurrentSubscriptionID
}

func (b business) clone(db *gorm.DB) business {
	b.businessDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b business) replaceDB(db *gorm.DB) business {
	b.businessDo.ReplaceDB(db)
	return b
}

type businessDo struct{ gen.DO }

type IBusinessDo interface {
	gen.SubQuery
	Debug() IBusinessDo
	WithContext(ctx context.Context) IBusinessDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IBusinessDo
	WriteDB() IBusinessDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IBusinessDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IBusinessDo
	Not(conds ...gen.Condition) IBusinessDo
	Or(conds ...gen.Condition) IBusinessDo
	Select(conds ...field.Expr) IBusinessDo
	Where(conds ...gen.Condition) IBusinessDo
	Order(conds ...field.Expr) IBusinessDo
	Distinct(cols ...field.Expr) IBusinessDo
	Omit(cols ...field.Expr) IBusinessDo
	Join(table schema.Tabler, on ...field.Expr) IBusinessDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IBusinessDo
	RightJoin(table schema.Tabler, on ...field.Expr) IBusinessDo
	Group(cols ...field.Expr) IBusinessDo
	Having(conds ...gen.Condition) IBusinessDo
	Limit(limit int) IBusinessDo
	Offset(offset int) IBusinessDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IBusinessDo
	Unscoped() IBusinessDo
	Create(values ...*model.Business) error
	CreateInBatches(values []*model.Business, batchSize int) error
	Save(values ...*model.Business) error
	First() (*model.Business, error)
	Take() (*model.Business, error)
	Last() (*model.Business, error)
	Find() ([]*model.Business, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Business, err error)
	FindInBatches(result *[]*model.Business, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Business) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IBusinessDo
	Assign(attrs ...field.AssignExpr) IBusinessDo
	Joins(fields ...field.RelationField) IBusinessDo
	Preload(fields ...field.RelationField) IBusinessDo
	FirstOrInit() (*model.Business, error)
	FirstOrCreate() (*model.Business, error)
	FindByPage(offset int, limit int) (result []*model.Business, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IBusinessDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (b businessDo) Debug() IBusinessDo {
	return b.withDO(b.DO.Debug())
}

func (b businessDo) WithContext(ctx context.Context) IBusinessDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b businessDo) ReadDB() IBusinessDo {
	return b.Clauses(dbresolver.Read)
}

func (b businessDo) WriteDB() IBusinessDo {
	return b.Clauses(dbresolver.Write)
}

func (b businessDo) Session(config *gorm.Session) IBusinessDo {
	return b.withDO(b.DO.Session(config))
}

func (b businessDo) Clauses(conds ...clause.Expression) IBusinessDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b businessDo) Returning(value interface{}, columns ...string) IBusinessDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b businessDo) Not(conds ...gen.Condition) IBusinessDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b businessDo) Or(conds ...gen.Condition) IBusinessDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b businessDo) Select(conds ...field.Expr) IBusinessDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b businessDo) Where(conds ...gen.Condition) IBusinessDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b businessDo) Order(conds ...field.Expr) IBusinessDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b businessDo) Distinct(cols ...field.Expr) IBusinessDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b businessDo) Omit(cols ...field.Expr) IBusinessDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b businessDo) Join(table schema.Tabler, on ...field.Expr) IBusinessDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b businessDo) LeftJoin(table schema.Tabler, on ...field.Expr) IBusinessDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b businessDo) RightJoin(table schema.Tabler, on ...field.Expr) IBusinessDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b businessDo) Group(cols ...field.Expr) IBusinessDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b businessDo) Having(conds ...gen.Condition) IBusinessDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b businessDo) Limit(limit int) IBusinessDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b businessDo) Offset(offset int) IBusinessDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b businessDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IBusinessDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b businessDo) Unscoped() IBusinessDo {
	return b.withDO(b.DO.Unscoped())
}

func (b businessDo) Create(values ...*model.Business) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b businessDo) CreateInBatches(values []*model.Business, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b businessDo) Save(values ...*model.Business) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b businessDo) First() (*model.Business, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Business), nil
	}
}

func (b businessDo) Take() (*model.Business, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Business), nil
	}
}

func (b businessDo) Last() (*model.Business, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Business), nil
	}
}

func (b businessDo) Find() ([]*model.Business, error) {
	result, err := b.DO.Find()
	return result.([]*model.Business), err
}

func (b businessDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Business, err error) {
	buf := make([]*model.Business, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b businessDo) FindInBatches(result *[]*model.Business, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b businessDo) Attrs(attrs ...field.AssignExpr) IBusinessDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b businessDo) Assign(attrs ...field.AssignExpr) IBusinessDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b businessDo) Joins(fields ...field.RelationField) IBusinessDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b businessDo) Preload(fields ...field.RelationField) IBusinessDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b businessDo) FirstOrInit() (*model.Business, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Business), nil
	}
}

func (b businessDo) FirstOrCreate() (*model.Business, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Business), nil
	}
}

func (b businessDo) FindByPage(offset int, limit int) (result []*model.Business, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b businessDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b businessDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b businessDo) Delete(models ...*model.Business) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *businessDo) withDO(do gen.Dao) *businessDo {
	b.DO = *do.(*gen.DO)
	return b
}
