// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend_go/model"
)

func newBusinessSubscription(db *gorm.DB, opts ...gen.DOOption) businessSubscription {
	_businessSubscription := businessSubscription{}

	_businessSubscription.businessSubscriptionDo.UseDB(db, opts...)
	_businessSubscription.businessSubscriptionDo.UseModel(&model.BusinessSubscription{})

	tableName := _businessSubscription.businessSubscriptionDo.TableName()
	_businessSubscription.ALL = field.NewAsterisk(tableName)
	_businessSubscription.ID = field.NewString(tableName, "id")
	_businessSubscription.Status = field.NewString(tableName, "status")
	_businessSubscription.StartDate = field.NewTime(tableName, "startDate")
	_businessSubscription.EndDate = field.NewTime(tableName, "endDate")
	_businessSubscription.BusinessID = field.NewString(tableName, "businessId")
	_businessSubscription.PlanID = field.NewString(tableName, "planId")
	_businessSubscription.AutoRenew = field.NewBool(tableName, "autoRenew")
	_businessSubscription.CreatedAt = field.NewTime(tableName, "createdAt")
	_businessSubscription.UpdatedAt = field.NewTime(tableName, "updatedAt")

	_businessSubscription.fillFieldMap()

	return _businessSubscription
}

type businessSubscription struct {
	businessSubscriptionDo

	ALL        field.Asterisk
	ID         field.String
	Status     field.String
	StartDate  field.Time
	EndDate    field.Time
	BusinessID field.String
	PlanID     field.String
	AutoRenew  field.Bool
	CreatedAt  field.Time
	UpdatedAt  field.Time

	fieldMap map[string]field.Expr
}

func (b businessSubscription) Table(newTableName string) *businessSubscription {
	b.businessSubscriptionDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b businessSubscription) As(alias string) *businessSubscription {
	b.businessSubscriptionDo.DO = *(b.businessSubscriptionDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *businessSubscription) updateTableName(table string) *businessSubscription {
	b.ALL = field.NewAsterisk(table)
	b.ID = field.NewString(table, "id")
	b.Status = field.NewString(table, "status")
	b.StartDate = field.NewTime(table, "startDate")
	b.EndDate = field.NewTime(table, "endDate")
	b.BusinessID = field.NewString(table, "businessId")
	b.PlanID = field.NewString(table, "planId")
	b.AutoRenew = field.NewBool(table, "autoRenew")
	b.CreatedAt = field.NewTime(table, "createdAt")
	b.UpdatedAt = field.NewTime(table, "updatedAt")

	b.fillFieldMap()

	return b
}

func (b *businessSubscription) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *businessSubscription) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 9)
	b.fieldMap["id"] = b.ID
	b.fieldMap["status"] = b.Status
	b.fieldMap["startDate"] = b.StartDate
	b.fieldMap["endDate"] = b.EndDate
	b.fieldMap["businessId"] = b.BusinessID
	b.fieldMap["planId"] = b.PlanID
	b.fieldMap["autoRenew"] = b.AutoRenew
	b.fieldMap["createdAt"] = b.CreatedAt
	b.fieldMap["updatedAt"] = b.UpdatedAt
}

func (b businessSubscription) clone(db *gorm.DB) businessSubscription {
	b.businessSubscriptionDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b businessSubscription) replaceDB(db *gorm.DB) businessSubscription {
	b.businessSubscriptionDo.ReplaceDB(db)
	return b
}

type businessSubscriptionDo struct{ gen.DO }

type IBusinessSubscriptionDo interface {
	gen.SubQuery
	Debug() IBusinessSubscriptionDo
	WithContext(ctx context.Context) IBusinessSubscriptionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IBusinessSubscriptionDo
	WriteDB() IBusinessSubscriptionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IBusinessSubscriptionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IBusinessSubscriptionDo
	Not(conds ...gen.Condition) IBusinessSubscriptionDo
	Or(conds ...gen.Condition) IBusinessSubscriptionDo
	Select(conds ...field.Expr) IBusinessSubscriptionDo
	Where(conds ...gen.Condition) IBusinessSubscriptionDo
	Order(conds ...field.Expr) IBusinessSubscriptionDo
	Distinct(cols ...field.Expr) IBusinessSubscriptionDo
	Omit(cols ...field.Expr) IBusinessSubscriptionDo
	Join(table schema.Tabler, on ...field.Expr) IBusinessSubscriptionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IBusinessSubscriptionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IBusinessSubscriptionDo
	Group(cols ...field.Expr) IBusinessSubscriptionDo
	Having(conds ...gen.Condition) IBusinessSubscriptionDo
	Limit(limit int) IBusinessSubscriptionDo
	Offset(offset int) IBusinessSubscriptionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IBusinessSubscriptionDo
	Unscoped() IBusinessSubscriptionDo
	Create(values ...*model.BusinessSubscription) error
	CreateInBatches(values []*model.BusinessSubscription, batchSize int) error
	Save(values ...*model.BusinessSubscription) error
	First() (*model.BusinessSubscription, error)
	Take() (*model.BusinessSubscription, error)
	Last() (*model.BusinessSubscription, error)
	Find() ([]*model.BusinessSubscription, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BusinessSubscription, err error)
	FindInBatches(result *[]*model.BusinessSubscription, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.BusinessSubscription) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IBusinessSubscriptionDo
	Assign(attrs ...field.AssignExpr) IBusinessSubscriptionDo
	Joins(fields ...field.RelationField) IBusinessSubscriptionDo
	Preload(fields ...field.RelationField) IBusinessSubscriptionDo
	FirstOrInit() (*model.BusinessSubscription, error)
	FirstOrCreate() (*model.BusinessSubscription, error)
	FindByPage(offset int, limit int) (result []*model.BusinessSubscription, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IBusinessSubscriptionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (b businessSubscriptionDo) Debug() IBusinessSubscriptionDo {
	return b.withDO(b.DO.Debug())
}

func (b businessSubscriptionDo) WithContext(ctx context.Context) IBusinessSubscriptionDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b businessSubscriptionDo) ReadDB() IBusinessSubscriptionDo {
	return b.Clauses(dbresolver.Read)
}

func (b businessSubscriptionDo) WriteDB() IBusinessSubscriptionDo {
	return b.Clauses(dbresolver.Write)
}

func (b businessSubscriptionDo) Session(config *gorm.Session) IBusinessSubscriptionDo {
	return b.withDO(b.DO.Session(config))
}

func (b businessSubscriptionDo) Clauses(conds ...clause.Expression) IBusinessSubscriptionDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b businessSubscriptionDo) Returning(value interface{}, columns ...string) IBusinessSubscriptionDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b businessSubscriptionDo) Not(conds ...gen.Condition) IBusinessSubscriptionDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b businessSubscriptionDo) Or(conds ...gen.Condition) IBusinessSubscriptionDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b businessSubscriptionDo) Select(conds ...field.Expr) IBusinessSubscriptionDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b businessSubscriptionDo) Where(conds ...gen.Condition) IBusinessSubscriptionDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b businessSubscriptionDo) Order(conds ...field.Expr) IBusinessSubscriptionDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b businessSubscriptionDo) Distinct(cols ...field.Expr) IBusinessSubscriptionDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b businessSubscriptionDo) Omit(cols ...field.Expr) IBusinessSubscriptionDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b businessSubscriptionDo) Join(table schema.Tabler, on ...field.Expr) IBusinessSubscriptionDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b businessSubscriptionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IBusinessSubscriptionDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b businessSubscriptionDo) RightJoin(table schema.Tabler, on ...field.Expr) IBusinessSubscriptionDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b businessSubscriptionDo) Group(cols ...field.Expr) IBusinessSubscriptionDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b businessSubscriptionDo) Having(conds ...gen.Condition) IBusinessSubscriptionDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b businessSubscriptionDo) Limit(limit int) IBusinessSubscriptionDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b businessSubscriptionDo) Offset(offset int) IBusinessSubscriptionDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b businessSubscriptionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IBusinessSubscriptionDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b businessSubscriptionDo) Unscoped() IBusinessSubscriptionDo {
	return b.withDO(b.DO.Unscoped())
}

func (b businessSubscriptionDo) Create(values ...*model.BusinessSubscription) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b businessSubscriptionDo) CreateInBatches(values []*model.BusinessSubscription, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b businessSubscriptionDo) Save(values ...*model.BusinessSubscription) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b businessSubscriptionDo) First() (*model.BusinessSubscription, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.BusinessSubscription), nil
	}
}

func (b businessSubscriptionDo) Take() (*model.BusinessSubscription, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.BusinessSubscription), nil
	}
}

func (b businessSubscriptionDo) Last() (*model.BusinessSubscription, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.BusinessSubscription), nil
	}
}

func (b businessSubscriptionDo) Find() ([]*model.BusinessSubscription, error) {
	result, err := b.DO.Find()
	return result.([]*model.BusinessSubscription), err
}

func (b businessSubscriptionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BusinessSubscription, err error) {
	buf := make([]*model.BusinessSubscription, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b businessSubscriptionDo) FindInBatches(result *[]*model.BusinessSubscription, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b businessSubscriptionDo) Attrs(attrs ...field.AssignExpr) IBusinessSubscriptionDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b businessSubscriptionDo) Assign(attrs ...field.AssignExpr) IBusinessSubscriptionDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b businessSubscriptionDo) Joins(fields ...field.RelationField) IBusinessSubscriptionDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b businessSubscriptionDo) Preload(fields ...field.RelationField) IBusinessSubscriptionDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b businessSubscriptionDo) FirstOrInit() (*model.BusinessSubscription, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.BusinessSubscription), nil
	}
}

func (b businessSubscriptionDo) FirstOrCreate() (*model.BusinessSubscription, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.BusinessSubscription), nil
	}
}

func (b businessSubscriptionDo) FindByPage(offset int, limit int) (result []*model.BusinessSubscription, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b businessSubscriptionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b businessSubscriptionDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b businessSubscriptionDo) Delete(models ...*model.BusinessSubscription) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *businessSubscriptionDo) withDO(do gen.Dao) *businessSubscriptionDo {
	b.DO = *do.(*gen.DO)
	return b
}
