// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                    = new(Query)
	Banner               *banner
	BookingSlot          *bookingSlot
	Business             *business
	BusinessSubscription *businessSubscription
	Expense              *expense
	GuestCustomer        *guestCustomer
	Membership           *membership
	Order                *order
	OrderItem            *orderItem
	Outlet               *outlet
	OutletOperatingHour  *outletOperatingHour
	Product              *product
	ProductGood          *productGood
	ProductMedium        *productMedium
	ProductService       *productService
	ProductTicket        *productTicket
	ReceiptSetting       *receiptSetting
	Staff                *staff
	StockLog             *stockLog
	SubscriptionInvoice  *subscriptionInvoice
	SubscriptionPlan     *subscriptionPlan
	TicketCode           *ticketCode
	TransactionRecord    *transactionRecord
	User                 *user
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Banner = &Q.Banner
	BookingSlot = &Q.BookingSlot
	Business = &Q.Business
	BusinessSubscription = &Q.BusinessSubscription
	Expense = &Q.Expense
	GuestCustomer = &Q.GuestCustomer
	Membership = &Q.Membership
	Order = &Q.Order
	OrderItem = &Q.OrderItem
	Outlet = &Q.Outlet
	OutletOperatingHour = &Q.OutletOperatingHour
	Product = &Q.Product
	ProductGood = &Q.ProductGood
	ProductMedium = &Q.ProductMedium
	ProductService = &Q.ProductService
	ProductTicket = &Q.ProductTicket
	ReceiptSetting = &Q.ReceiptSetting
	Staff = &Q.Staff
	StockLog = &Q.StockLog
	SubscriptionInvoice = &Q.SubscriptionInvoice
	SubscriptionPlan = &Q.SubscriptionPlan
	TicketCode = &Q.TicketCode
	TransactionRecord = &Q.TransactionRecord
	User = &Q.User
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                   db,
		Banner:               newBanner(db, opts...),
		BookingSlot:          newBookingSlot(db, opts...),
		Business:             newBusiness(db, opts...),
		BusinessSubscription: newBusinessSubscription(db, opts...),
		Expense:              newExpense(db, opts...),
		GuestCustomer:        newGuestCustomer(db, opts...),
		Membership:           newMembership(db, opts...),
		Order:                newOrder(db, opts...),
		OrderItem:            newOrderItem(db, opts...),
		Outlet:               newOutlet(db, opts...),
		OutletOperatingHour:  newOutletOperatingHour(db, opts...),
		Product:              newProduct(db, opts...),
		ProductGood:          newProductGood(db, opts...),
		ProductMedium:        newProductMedium(db, opts...),
		ProductService:       newProductService(db, opts...),
		ProductTicket:        newProductTicket(db, opts...),
		ReceiptSetting:       newReceiptSetting(db, opts...),
		Staff:                newStaff(db, opts...),
		StockLog:             newStockLog(db, opts...),
		SubscriptionInvoice:  newSubscriptionInvoice(db, opts...),
		SubscriptionPlan:     newSubscriptionPlan(db, opts...),
		TicketCode:           newTicketCode(db, opts...),
		TransactionRecord:    newTransactionRecord(db, opts...),
		User:                 newUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Banner               banner
	BookingSlot          bookingSlot
	Business             business
	BusinessSubscription businessSubscription
	Expense              expense
	GuestCustomer        guestCustomer
	Membership           membership
	Order                order
	OrderItem            orderItem
	Outlet               outlet
	OutletOperatingHour  outletOperatingHour
	Product              product
	ProductGood          productGood
	ProductMedium        productMedium
	ProductService       productService
	ProductTicket        productTicket
	ReceiptSetting       receiptSetting
	Staff                staff
	StockLog             stockLog
	SubscriptionInvoice  subscriptionInvoice
	SubscriptionPlan     subscriptionPlan
	TicketCode           ticketCode
	TransactionRecord    transactionRecord
	User                 user
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                   db,
		Banner:               q.Banner.clone(db),
		BookingSlot:          q.BookingSlot.clone(db),
		Business:             q.Business.clone(db),
		BusinessSubscription: q.BusinessSubscription.clone(db),
		Expense:              q.Expense.clone(db),
		GuestCustomer:        q.GuestCustomer.clone(db),
		Membership:           q.Membership.clone(db),
		Order:                q.Order.clone(db),
		OrderItem:            q.OrderItem.clone(db),
		Outlet:               q.Outlet.clone(db),
		OutletOperatingHour:  q.OutletOperatingHour.clone(db),
		Product:              q.Product.clone(db),
		ProductGood:          q.ProductGood.clone(db),
		ProductMedium:        q.ProductMedium.clone(db),
		ProductService:       q.ProductService.clone(db),
		ProductTicket:        q.ProductTicket.clone(db),
		ReceiptSetting:       q.ReceiptSetting.clone(db),
		Staff:                q.Staff.clone(db),
		StockLog:             q.StockLog.clone(db),
		SubscriptionInvoice:  q.SubscriptionInvoice.clone(db),
		SubscriptionPlan:     q.SubscriptionPlan.clone(db),
		TicketCode:           q.TicketCode.clone(db),
		TransactionRecord:    q.TransactionRecord.clone(db),
		User:                 q.User.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                   db,
		Banner:               q.Banner.replaceDB(db),
		BookingSlot:          q.BookingSlot.replaceDB(db),
		Business:             q.Business.replaceDB(db),
		BusinessSubscription: q.BusinessSubscription.replaceDB(db),
		Expense:              q.Expense.replaceDB(db),
		GuestCustomer:        q.GuestCustomer.replaceDB(db),
		Membership:           q.Membership.replaceDB(db),
		Order:                q.Order.replaceDB(db),
		OrderItem:            q.OrderItem.replaceDB(db),
		Outlet:               q.Outlet.replaceDB(db),
		OutletOperatingHour:  q.OutletOperatingHour.replaceDB(db),
		Product:              q.Product.replaceDB(db),
		ProductGood:          q.ProductGood.replaceDB(db),
		ProductMedium:        q.ProductMedium.replaceDB(db),
		ProductService:       q.ProductService.replaceDB(db),
		ProductTicket:        q.ProductTicket.replaceDB(db),
		ReceiptSetting:       q.ReceiptSetting.replaceDB(db),
		Staff:                q.Staff.replaceDB(db),
		StockLog:             q.StockLog.replaceDB(db),
		SubscriptionInvoice:  q.SubscriptionInvoice.replaceDB(db),
		SubscriptionPlan:     q.SubscriptionPlan.replaceDB(db),
		TicketCode:           q.TicketCode.replaceDB(db),
		TransactionRecord:    q.TransactionRecord.replaceDB(db),
		User:                 q.User.replaceDB(db),
	}
}

type queryCtx struct {
	Banner               IBannerDo
	BookingSlot          IBookingSlotDo
	Business             IBusinessDo
	BusinessSubscription IBusinessSubscriptionDo
	Expense              IExpenseDo
	GuestCustomer        IGuestCustomerDo
	Membership           IMembershipDo
	Order                IOrderDo
	OrderItem            IOrderItemDo
	Outlet               IOutletDo
	OutletOperatingHour  IOutletOperatingHourDo
	Product              IProductDo
	ProductGood          IProductGoodDo
	ProductMedium        IProductMediumDo
	ProductService       IProductServiceDo
	ProductTicket        IProductTicketDo
	ReceiptSetting       IReceiptSettingDo
	Staff                IStaffDo
	StockLog             IStockLogDo
	SubscriptionInvoice  ISubscriptionInvoiceDo
	SubscriptionPlan     ISubscriptionPlanDo
	TicketCode           ITicketCodeDo
	TransactionRecord    ITransactionRecordDo
	User                 IUserDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Banner:               q.Banner.WithContext(ctx),
		BookingSlot:          q.BookingSlot.WithContext(ctx),
		Business:             q.Business.WithContext(ctx),
		BusinessSubscription: q.BusinessSubscription.WithContext(ctx),
		Expense:              q.Expense.WithContext(ctx),
		GuestCustomer:        q.GuestCustomer.WithContext(ctx),
		Membership:           q.Membership.WithContext(ctx),
		Order:                q.Order.WithContext(ctx),
		OrderItem:            q.OrderItem.WithContext(ctx),
		Outlet:               q.Outlet.WithContext(ctx),
		OutletOperatingHour:  q.OutletOperatingHour.WithContext(ctx),
		Product:              q.Product.WithContext(ctx),
		ProductGood:          q.ProductGood.WithContext(ctx),
		ProductMedium:        q.ProductMedium.WithContext(ctx),
		ProductService:       q.ProductService.WithContext(ctx),
		ProductTicket:        q.ProductTicket.WithContext(ctx),
		ReceiptSetting:       q.ReceiptSetting.WithContext(ctx),
		Staff:                q.Staff.WithContext(ctx),
		StockLog:             q.StockLog.WithContext(ctx),
		SubscriptionInvoice:  q.SubscriptionInvoice.WithContext(ctx),
		SubscriptionPlan:     q.SubscriptionPlan.WithContext(ctx),
		TicketCode:           q.TicketCode.WithContext(ctx),
		TransactionRecord:    q.TransactionRecord.WithContext(ctx),
		User:                 q.User.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
