// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend_go/model"
)

func newGuestCustomer(db *gorm.DB, opts ...gen.DOOption) guestCustomer {
	_guestCustomer := guestCustomer{}

	_guestCustomer.guestCustomerDo.UseDB(db, opts...)
	_guestCustomer.guestCustomerDo.UseModel(&model.GuestCustomer{})

	tableName := _guestCustomer.guestCustomerDo.TableName()
	_guestCustomer.ALL = field.NewAsterisk(tableName)
	_guestCustomer.ID = field.NewString(tableName, "id")
	_guestCustomer.Name = field.NewString(tableName, "name")
	_guestCustomer.Email = field.NewString(tableName, "email")
	_guestCustomer.Phone = field.NewString(tableName, "phone")
	_guestCustomer.CreatedAt = field.NewTime(tableName, "createdAt")

	_guestCustomer.fillFieldMap()

	return _guestCustomer
}

type guestCustomer struct {
	guestCustomerDo

	ALL       field.Asterisk
	ID        field.String
	Name      field.String
	Email     field.String
	Phone     field.String
	CreatedAt field.Time

	fieldMap map[string]field.Expr
}

func (g guestCustomer) Table(newTableName string) *guestCustomer {
	g.guestCustomerDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g guestCustomer) As(alias string) *guestCustomer {
	g.guestCustomerDo.DO = *(g.guestCustomerDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *guestCustomer) updateTableName(table string) *guestCustomer {
	g.ALL = field.NewAsterisk(table)
	g.ID = field.NewString(table, "id")
	g.Name = field.NewString(table, "name")
	g.Email = field.NewString(table, "email")
	g.Phone = field.NewString(table, "phone")
	g.CreatedAt = field.NewTime(table, "createdAt")

	g.fillFieldMap()

	return g
}

func (g *guestCustomer) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *guestCustomer) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 5)
	g.fieldMap["id"] = g.ID
	g.fieldMap["name"] = g.Name
	g.fieldMap["email"] = g.Email
	g.fieldMap["phone"] = g.Phone
	g.fieldMap["createdAt"] = g.CreatedAt
}

func (g guestCustomer) clone(db *gorm.DB) guestCustomer {
	g.guestCustomerDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g guestCustomer) replaceDB(db *gorm.DB) guestCustomer {
	g.guestCustomerDo.ReplaceDB(db)
	return g
}

type guestCustomerDo struct{ gen.DO }

type IGuestCustomerDo interface {
	gen.SubQuery
	Debug() IGuestCustomerDo
	WithContext(ctx context.Context) IGuestCustomerDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IGuestCustomerDo
	WriteDB() IGuestCustomerDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IGuestCustomerDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IGuestCustomerDo
	Not(conds ...gen.Condition) IGuestCustomerDo
	Or(conds ...gen.Condition) IGuestCustomerDo
	Select(conds ...field.Expr) IGuestCustomerDo
	Where(conds ...gen.Condition) IGuestCustomerDo
	Order(conds ...field.Expr) IGuestCustomerDo
	Distinct(cols ...field.Expr) IGuestCustomerDo
	Omit(cols ...field.Expr) IGuestCustomerDo
	Join(table schema.Tabler, on ...field.Expr) IGuestCustomerDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IGuestCustomerDo
	RightJoin(table schema.Tabler, on ...field.Expr) IGuestCustomerDo
	Group(cols ...field.Expr) IGuestCustomerDo
	Having(conds ...gen.Condition) IGuestCustomerDo
	Limit(limit int) IGuestCustomerDo
	Offset(offset int) IGuestCustomerDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IGuestCustomerDo
	Unscoped() IGuestCustomerDo
	Create(values ...*model.GuestCustomer) error
	CreateInBatches(values []*model.GuestCustomer, batchSize int) error
	Save(values ...*model.GuestCustomer) error
	First() (*model.GuestCustomer, error)
	Take() (*model.GuestCustomer, error)
	Last() (*model.GuestCustomer, error)
	Find() ([]*model.GuestCustomer, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GuestCustomer, err error)
	FindInBatches(result *[]*model.GuestCustomer, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.GuestCustomer) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IGuestCustomerDo
	Assign(attrs ...field.AssignExpr) IGuestCustomerDo
	Joins(fields ...field.RelationField) IGuestCustomerDo
	Preload(fields ...field.RelationField) IGuestCustomerDo
	FirstOrInit() (*model.GuestCustomer, error)
	FirstOrCreate() (*model.GuestCustomer, error)
	FindByPage(offset int, limit int) (result []*model.GuestCustomer, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IGuestCustomerDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (g guestCustomerDo) Debug() IGuestCustomerDo {
	return g.withDO(g.DO.Debug())
}

func (g guestCustomerDo) WithContext(ctx context.Context) IGuestCustomerDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g guestCustomerDo) ReadDB() IGuestCustomerDo {
	return g.Clauses(dbresolver.Read)
}

func (g guestCustomerDo) WriteDB() IGuestCustomerDo {
	return g.Clauses(dbresolver.Write)
}

func (g guestCustomerDo) Session(config *gorm.Session) IGuestCustomerDo {
	return g.withDO(g.DO.Session(config))
}

func (g guestCustomerDo) Clauses(conds ...clause.Expression) IGuestCustomerDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g guestCustomerDo) Returning(value interface{}, columns ...string) IGuestCustomerDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g guestCustomerDo) Not(conds ...gen.Condition) IGuestCustomerDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g guestCustomerDo) Or(conds ...gen.Condition) IGuestCustomerDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g guestCustomerDo) Select(conds ...field.Expr) IGuestCustomerDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g guestCustomerDo) Where(conds ...gen.Condition) IGuestCustomerDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g guestCustomerDo) Order(conds ...field.Expr) IGuestCustomerDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g guestCustomerDo) Distinct(cols ...field.Expr) IGuestCustomerDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g guestCustomerDo) Omit(cols ...field.Expr) IGuestCustomerDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g guestCustomerDo) Join(table schema.Tabler, on ...field.Expr) IGuestCustomerDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g guestCustomerDo) LeftJoin(table schema.Tabler, on ...field.Expr) IGuestCustomerDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g guestCustomerDo) RightJoin(table schema.Tabler, on ...field.Expr) IGuestCustomerDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g guestCustomerDo) Group(cols ...field.Expr) IGuestCustomerDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g guestCustomerDo) Having(conds ...gen.Condition) IGuestCustomerDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g guestCustomerDo) Limit(limit int) IGuestCustomerDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g guestCustomerDo) Offset(offset int) IGuestCustomerDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g guestCustomerDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IGuestCustomerDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g guestCustomerDo) Unscoped() IGuestCustomerDo {
	return g.withDO(g.DO.Unscoped())
}

func (g guestCustomerDo) Create(values ...*model.GuestCustomer) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g guestCustomerDo) CreateInBatches(values []*model.GuestCustomer, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g guestCustomerDo) Save(values ...*model.GuestCustomer) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g guestCustomerDo) First() (*model.GuestCustomer, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.GuestCustomer), nil
	}
}

func (g guestCustomerDo) Take() (*model.GuestCustomer, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.GuestCustomer), nil
	}
}

func (g guestCustomerDo) Last() (*model.GuestCustomer, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.GuestCustomer), nil
	}
}

func (g guestCustomerDo) Find() ([]*model.GuestCustomer, error) {
	result, err := g.DO.Find()
	return result.([]*model.GuestCustomer), err
}

func (g guestCustomerDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GuestCustomer, err error) {
	buf := make([]*model.GuestCustomer, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g guestCustomerDo) FindInBatches(result *[]*model.GuestCustomer, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g guestCustomerDo) Attrs(attrs ...field.AssignExpr) IGuestCustomerDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g guestCustomerDo) Assign(attrs ...field.AssignExpr) IGuestCustomerDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g guestCustomerDo) Joins(fields ...field.RelationField) IGuestCustomerDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g guestCustomerDo) Preload(fields ...field.RelationField) IGuestCustomerDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g guestCustomerDo) FirstOrInit() (*model.GuestCustomer, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.GuestCustomer), nil
	}
}

func (g guestCustomerDo) FirstOrCreate() (*model.GuestCustomer, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.GuestCustomer), nil
	}
}

func (g guestCustomerDo) FindByPage(offset int, limit int) (result []*model.GuestCustomer, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g guestCustomerDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g guestCustomerDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g guestCustomerDo) Delete(models ...*model.GuestCustomer) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *guestCustomerDo) withDO(do gen.Dao) *guestCustomerDo {
	g.DO = *do.(*gen.DO)
	return g
}
