// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend_go/model"
)

func newOutletOperatingHour(db *gorm.DB, opts ...gen.DOOption) outletOperatingHour {
	_outletOperatingHour := outletOperatingHour{}

	_outletOperatingHour.outletOperatingHourDo.UseDB(db, opts...)
	_outletOperatingHour.outletOperatingHourDo.UseModel(&model.OutletOperatingHour{})

	tableName := _outletOperatingHour.outletOperatingHourDo.TableName()
	_outletOperatingHour.ALL = field.NewAsterisk(tableName)
	_outletOperatingHour.ID = field.NewString(tableName, "id")
	_outletOperatingHour.DayOfWeek = field.NewInt32(tableName, "dayOfWeek")
	_outletOperatingHour.OpenTime = field.NewTime(tableName, "openTime")
	_outletOperatingHour.CloseTime = field.NewTime(tableName, "closeTime")
	_outletOperatingHour.IsOpen = field.NewBool(tableName, "isOpen")
	_outletOperatingHour.OutletID = field.NewString(tableName, "outletId")
	_outletOperatingHour.CreatedAt = field.NewTime(tableName, "createdAt")
	_outletOperatingHour.UpdatedAt = field.NewTime(tableName, "updatedAt")

	_outletOperatingHour.fillFieldMap()

	return _outletOperatingHour
}

type outletOperatingHour struct {
	outletOperatingHourDo

	ALL       field.Asterisk
	ID        field.String
	DayOfWeek field.Int32
	OpenTime  field.Time
	CloseTime field.Time
	IsOpen    field.Bool
	OutletID  field.String
	CreatedAt field.Time
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

func (o outletOperatingHour) Table(newTableName string) *outletOperatingHour {
	o.outletOperatingHourDo.UseTable(newTableName)
	return o.updateTableName(newTableName)
}

func (o outletOperatingHour) As(alias string) *outletOperatingHour {
	o.outletOperatingHourDo.DO = *(o.outletOperatingHourDo.As(alias).(*gen.DO))
	return o.updateTableName(alias)
}

func (o *outletOperatingHour) updateTableName(table string) *outletOperatingHour {
	o.ALL = field.NewAsterisk(table)
	o.ID = field.NewString(table, "id")
	o.DayOfWeek = field.NewInt32(table, "dayOfWeek")
	o.OpenTime = field.NewTime(table, "openTime")
	o.CloseTime = field.NewTime(table, "closeTime")
	o.IsOpen = field.NewBool(table, "isOpen")
	o.OutletID = field.NewString(table, "outletId")
	o.CreatedAt = field.NewTime(table, "createdAt")
	o.UpdatedAt = field.NewTime(table, "updatedAt")

	o.fillFieldMap()

	return o
}

func (o *outletOperatingHour) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := o.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (o *outletOperatingHour) fillFieldMap() {
	o.fieldMap = make(map[string]field.Expr, 8)
	o.fieldMap["id"] = o.ID
	o.fieldMap["dayOfWeek"] = o.DayOfWeek
	o.fieldMap["openTime"] = o.OpenTime
	o.fieldMap["closeTime"] = o.CloseTime
	o.fieldMap["isOpen"] = o.IsOpen
	o.fieldMap["outletId"] = o.OutletID
	o.fieldMap["createdAt"] = o.CreatedAt
	o.fieldMap["updatedAt"] = o.UpdatedAt
}

func (o outletOperatingHour) clone(db *gorm.DB) outletOperatingHour {
	o.outletOperatingHourDo.ReplaceConnPool(db.Statement.ConnPool)
	return o
}

func (o outletOperatingHour) replaceDB(db *gorm.DB) outletOperatingHour {
	o.outletOperatingHourDo.ReplaceDB(db)
	return o
}

type outletOperatingHourDo struct{ gen.DO }

type IOutletOperatingHourDo interface {
	gen.SubQuery
	Debug() IOutletOperatingHourDo
	WithContext(ctx context.Context) IOutletOperatingHourDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IOutletOperatingHourDo
	WriteDB() IOutletOperatingHourDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IOutletOperatingHourDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IOutletOperatingHourDo
	Not(conds ...gen.Condition) IOutletOperatingHourDo
	Or(conds ...gen.Condition) IOutletOperatingHourDo
	Select(conds ...field.Expr) IOutletOperatingHourDo
	Where(conds ...gen.Condition) IOutletOperatingHourDo
	Order(conds ...field.Expr) IOutletOperatingHourDo
	Distinct(cols ...field.Expr) IOutletOperatingHourDo
	Omit(cols ...field.Expr) IOutletOperatingHourDo
	Join(table schema.Tabler, on ...field.Expr) IOutletOperatingHourDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IOutletOperatingHourDo
	RightJoin(table schema.Tabler, on ...field.Expr) IOutletOperatingHourDo
	Group(cols ...field.Expr) IOutletOperatingHourDo
	Having(conds ...gen.Condition) IOutletOperatingHourDo
	Limit(limit int) IOutletOperatingHourDo
	Offset(offset int) IOutletOperatingHourDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IOutletOperatingHourDo
	Unscoped() IOutletOperatingHourDo
	Create(values ...*model.OutletOperatingHour) error
	CreateInBatches(values []*model.OutletOperatingHour, batchSize int) error
	Save(values ...*model.OutletOperatingHour) error
	First() (*model.OutletOperatingHour, error)
	Take() (*model.OutletOperatingHour, error)
	Last() (*model.OutletOperatingHour, error)
	Find() ([]*model.OutletOperatingHour, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.OutletOperatingHour, err error)
	FindInBatches(result *[]*model.OutletOperatingHour, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.OutletOperatingHour) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IOutletOperatingHourDo
	Assign(attrs ...field.AssignExpr) IOutletOperatingHourDo
	Joins(fields ...field.RelationField) IOutletOperatingHourDo
	Preload(fields ...field.RelationField) IOutletOperatingHourDo
	FirstOrInit() (*model.OutletOperatingHour, error)
	FirstOrCreate() (*model.OutletOperatingHour, error)
	FindByPage(offset int, limit int) (result []*model.OutletOperatingHour, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IOutletOperatingHourDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (o outletOperatingHourDo) Debug() IOutletOperatingHourDo {
	return o.withDO(o.DO.Debug())
}

func (o outletOperatingHourDo) WithContext(ctx context.Context) IOutletOperatingHourDo {
	return o.withDO(o.DO.WithContext(ctx))
}

func (o outletOperatingHourDo) ReadDB() IOutletOperatingHourDo {
	return o.Clauses(dbresolver.Read)
}

func (o outletOperatingHourDo) WriteDB() IOutletOperatingHourDo {
	return o.Clauses(dbresolver.Write)
}

func (o outletOperatingHourDo) Session(config *gorm.Session) IOutletOperatingHourDo {
	return o.withDO(o.DO.Session(config))
}

func (o outletOperatingHourDo) Clauses(conds ...clause.Expression) IOutletOperatingHourDo {
	return o.withDO(o.DO.Clauses(conds...))
}

func (o outletOperatingHourDo) Returning(value interface{}, columns ...string) IOutletOperatingHourDo {
	return o.withDO(o.DO.Returning(value, columns...))
}

func (o outletOperatingHourDo) Not(conds ...gen.Condition) IOutletOperatingHourDo {
	return o.withDO(o.DO.Not(conds...))
}

func (o outletOperatingHourDo) Or(conds ...gen.Condition) IOutletOperatingHourDo {
	return o.withDO(o.DO.Or(conds...))
}

func (o outletOperatingHourDo) Select(conds ...field.Expr) IOutletOperatingHourDo {
	return o.withDO(o.DO.Select(conds...))
}

func (o outletOperatingHourDo) Where(conds ...gen.Condition) IOutletOperatingHourDo {
	return o.withDO(o.DO.Where(conds...))
}

func (o outletOperatingHourDo) Order(conds ...field.Expr) IOutletOperatingHourDo {
	return o.withDO(o.DO.Order(conds...))
}

func (o outletOperatingHourDo) Distinct(cols ...field.Expr) IOutletOperatingHourDo {
	return o.withDO(o.DO.Distinct(cols...))
}

func (o outletOperatingHourDo) Omit(cols ...field.Expr) IOutletOperatingHourDo {
	return o.withDO(o.DO.Omit(cols...))
}

func (o outletOperatingHourDo) Join(table schema.Tabler, on ...field.Expr) IOutletOperatingHourDo {
	return o.withDO(o.DO.Join(table, on...))
}

func (o outletOperatingHourDo) LeftJoin(table schema.Tabler, on ...field.Expr) IOutletOperatingHourDo {
	return o.withDO(o.DO.LeftJoin(table, on...))
}

func (o outletOperatingHourDo) RightJoin(table schema.Tabler, on ...field.Expr) IOutletOperatingHourDo {
	return o.withDO(o.DO.RightJoin(table, on...))
}

func (o outletOperatingHourDo) Group(cols ...field.Expr) IOutletOperatingHourDo {
	return o.withDO(o.DO.Group(cols...))
}

func (o outletOperatingHourDo) Having(conds ...gen.Condition) IOutletOperatingHourDo {
	return o.withDO(o.DO.Having(conds...))
}

func (o outletOperatingHourDo) Limit(limit int) IOutletOperatingHourDo {
	return o.withDO(o.DO.Limit(limit))
}

func (o outletOperatingHourDo) Offset(offset int) IOutletOperatingHourDo {
	return o.withDO(o.DO.Offset(offset))
}

func (o outletOperatingHourDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IOutletOperatingHourDo {
	return o.withDO(o.DO.Scopes(funcs...))
}

func (o outletOperatingHourDo) Unscoped() IOutletOperatingHourDo {
	return o.withDO(o.DO.Unscoped())
}

func (o outletOperatingHourDo) Create(values ...*model.OutletOperatingHour) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Create(values)
}

func (o outletOperatingHourDo) CreateInBatches(values []*model.OutletOperatingHour, batchSize int) error {
	return o.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (o outletOperatingHourDo) Save(values ...*model.OutletOperatingHour) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Save(values)
}

func (o outletOperatingHourDo) First() (*model.OutletOperatingHour, error) {
	if result, err := o.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.OutletOperatingHour), nil
	}
}

func (o outletOperatingHourDo) Take() (*model.OutletOperatingHour, error) {
	if result, err := o.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.OutletOperatingHour), nil
	}
}

func (o outletOperatingHourDo) Last() (*model.OutletOperatingHour, error) {
	if result, err := o.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.OutletOperatingHour), nil
	}
}

func (o outletOperatingHourDo) Find() ([]*model.OutletOperatingHour, error) {
	result, err := o.DO.Find()
	return result.([]*model.OutletOperatingHour), err
}

func (o outletOperatingHourDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.OutletOperatingHour, err error) {
	buf := make([]*model.OutletOperatingHour, 0, batchSize)
	err = o.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (o outletOperatingHourDo) FindInBatches(result *[]*model.OutletOperatingHour, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return o.DO.FindInBatches(result, batchSize, fc)
}

func (o outletOperatingHourDo) Attrs(attrs ...field.AssignExpr) IOutletOperatingHourDo {
	return o.withDO(o.DO.Attrs(attrs...))
}

func (o outletOperatingHourDo) Assign(attrs ...field.AssignExpr) IOutletOperatingHourDo {
	return o.withDO(o.DO.Assign(attrs...))
}

func (o outletOperatingHourDo) Joins(fields ...field.RelationField) IOutletOperatingHourDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Joins(_f))
	}
	return &o
}

func (o outletOperatingHourDo) Preload(fields ...field.RelationField) IOutletOperatingHourDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Preload(_f))
	}
	return &o
}

func (o outletOperatingHourDo) FirstOrInit() (*model.OutletOperatingHour, error) {
	if result, err := o.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.OutletOperatingHour), nil
	}
}

func (o outletOperatingHourDo) FirstOrCreate() (*model.OutletOperatingHour, error) {
	if result, err := o.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.OutletOperatingHour), nil
	}
}

func (o outletOperatingHourDo) FindByPage(offset int, limit int) (result []*model.OutletOperatingHour, count int64, err error) {
	result, err = o.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = o.Offset(-1).Limit(-1).Count()
	return
}

func (o outletOperatingHourDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = o.Count()
	if err != nil {
		return
	}

	err = o.Offset(offset).Limit(limit).Scan(result)
	return
}

func (o outletOperatingHourDo) Scan(result interface{}) (err error) {
	return o.DO.Scan(result)
}

func (o outletOperatingHourDo) Delete(models ...*model.OutletOperatingHour) (result gen.ResultInfo, err error) {
	return o.DO.Delete(models)
}

func (o *outletOperatingHourDo) withDO(do gen.Dao) *outletOperatingHourDo {
	o.DO = *do.(*gen.DO)
	return o
}
