// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend_go/model"
)

func newProductService(db *gorm.DB, opts ...gen.DOOption) productService {
	_productService := productService{}

	_productService.productServiceDo.UseDB(db, opts...)
	_productService.productServiceDo.UseModel(&model.ProductService{})

	tableName := _productService.productServiceDo.TableName()
	_productService.ALL = field.NewAsterisk(tableName)
	_productService.ID = field.NewString(tableName, "id")
	_productService.ProductID = field.NewString(tableName, "productId")
	_productService.DurationMinutes = field.NewInt32(tableName, "durationMinutes")
	_productService.SellingPrice = field.NewFloat64(tableName, "sellingPrice")
	_productService.ProviderName = field.NewString(tableName, "providerName")
	_productService.ProviderPhone = field.NewString(tableName, "providerPhone")
	_productService.ProviderEmail = field.NewString(tableName, "providerEmail")
	_productService.CommissionType = field.NewString(tableName, "commissionType")
	_productService.CommissionValue = field.NewFloat64(tableName, "commissionValue")
	_productService.MaxParallel = field.NewInt32(tableName, "maxParallel")
	_productService.CreatedAt = field.NewTime(tableName, "createdAt")
	_productService.UpdatedAt = field.NewTime(tableName, "updatedAt")
	_productService.BookingInWorkHours = field.NewBool(tableName, "bookingInWorkHours")
	_productService.FridayClose = field.NewTime(tableName, "fridayClose")
	_productService.FridayOpen = field.NewTime(tableName, "fridayOpen")
	_productService.MondayClose = field.NewTime(tableName, "mondayClose")
	_productService.MondayOpen = field.NewTime(tableName, "mondayOpen")
	_productService.SaturdayClose = field.NewTime(tableName, "saturdayClose")
	_productService.SaturdayOpen = field.NewTime(tableName, "saturdayOpen")
	_productService.SundayClose = field.NewTime(tableName, "sundayClose")
	_productService.SundayOpen = field.NewTime(tableName, "sundayOpen")
	_productService.ThursdayClose = field.NewTime(tableName, "thursdayClose")
	_productService.ThursdayOpen = field.NewTime(tableName, "thursdayOpen")
	_productService.TuesdayClose = field.NewTime(tableName, "tuesdayClose")
	_productService.TuesdayOpen = field.NewTime(tableName, "tuesdayOpen")
	_productService.WednesdayClose = field.NewTime(tableName, "wednesdayClose")
	_productService.WednesdayOpen = field.NewTime(tableName, "wednesdayOpen")

	_productService.fillFieldMap()

	return _productService
}

type productService struct {
	productServiceDo

	ALL                field.Asterisk
	ID                 field.String
	ProductID          field.String
	DurationMinutes    field.Int32
	SellingPrice       field.Float64
	ProviderName       field.String
	ProviderPhone      field.String
	ProviderEmail      field.String
	CommissionType     field.String
	CommissionValue    field.Float64
	MaxParallel        field.Int32
	CreatedAt          field.Time
	UpdatedAt          field.Time
	BookingInWorkHours field.Bool
	FridayClose        field.Time
	FridayOpen         field.Time
	MondayClose        field.Time
	MondayOpen         field.Time
	SaturdayClose      field.Time
	SaturdayOpen       field.Time
	SundayClose        field.Time
	SundayOpen         field.Time
	ThursdayClose      field.Time
	ThursdayOpen       field.Time
	TuesdayClose       field.Time
	TuesdayOpen        field.Time
	WednesdayClose     field.Time
	WednesdayOpen      field.Time

	fieldMap map[string]field.Expr
}

func (p productService) Table(newTableName string) *productService {
	p.productServiceDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p productService) As(alias string) *productService {
	p.productServiceDo.DO = *(p.productServiceDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *productService) updateTableName(table string) *productService {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewString(table, "id")
	p.ProductID = field.NewString(table, "productId")
	p.DurationMinutes = field.NewInt32(table, "durationMinutes")
	p.SellingPrice = field.NewFloat64(table, "sellingPrice")
	p.ProviderName = field.NewString(table, "providerName")
	p.ProviderPhone = field.NewString(table, "providerPhone")
	p.ProviderEmail = field.NewString(table, "providerEmail")
	p.CommissionType = field.NewString(table, "commissionType")
	p.CommissionValue = field.NewFloat64(table, "commissionValue")
	p.MaxParallel = field.NewInt32(table, "maxParallel")
	p.CreatedAt = field.NewTime(table, "createdAt")
	p.UpdatedAt = field.NewTime(table, "updatedAt")
	p.BookingInWorkHours = field.NewBool(table, "bookingInWorkHours")
	p.FridayClose = field.NewTime(table, "fridayClose")
	p.FridayOpen = field.NewTime(table, "fridayOpen")
	p.MondayClose = field.NewTime(table, "mondayClose")
	p.MondayOpen = field.NewTime(table, "mondayOpen")
	p.SaturdayClose = field.NewTime(table, "saturdayClose")
	p.SaturdayOpen = field.NewTime(table, "saturdayOpen")
	p.SundayClose = field.NewTime(table, "sundayClose")
	p.SundayOpen = field.NewTime(table, "sundayOpen")
	p.ThursdayClose = field.NewTime(table, "thursdayClose")
	p.ThursdayOpen = field.NewTime(table, "thursdayOpen")
	p.TuesdayClose = field.NewTime(table, "tuesdayClose")
	p.TuesdayOpen = field.NewTime(table, "tuesdayOpen")
	p.WednesdayClose = field.NewTime(table, "wednesdayClose")
	p.WednesdayOpen = field.NewTime(table, "wednesdayOpen")

	p.fillFieldMap()

	return p
}

func (p *productService) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *productService) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 27)
	p.fieldMap["id"] = p.ID
	p.fieldMap["productId"] = p.ProductID
	p.fieldMap["durationMinutes"] = p.DurationMinutes
	p.fieldMap["sellingPrice"] = p.SellingPrice
	p.fieldMap["providerName"] = p.ProviderName
	p.fieldMap["providerPhone"] = p.ProviderPhone
	p.fieldMap["providerEmail"] = p.ProviderEmail
	p.fieldMap["commissionType"] = p.CommissionType
	p.fieldMap["commissionValue"] = p.CommissionValue
	p.fieldMap["maxParallel"] = p.MaxParallel
	p.fieldMap["createdAt"] = p.CreatedAt
	p.fieldMap["updatedAt"] = p.UpdatedAt
	p.fieldMap["bookingInWorkHours"] = p.BookingInWorkHours
	p.fieldMap["fridayClose"] = p.FridayClose
	p.fieldMap["fridayOpen"] = p.FridayOpen
	p.fieldMap["mondayClose"] = p.MondayClose
	p.fieldMap["mondayOpen"] = p.MondayOpen
	p.fieldMap["saturdayClose"] = p.SaturdayClose
	p.fieldMap["saturdayOpen"] = p.SaturdayOpen
	p.fieldMap["sundayClose"] = p.SundayClose
	p.fieldMap["sundayOpen"] = p.SundayOpen
	p.fieldMap["thursdayClose"] = p.ThursdayClose
	p.fieldMap["thursdayOpen"] = p.ThursdayOpen
	p.fieldMap["tuesdayClose"] = p.TuesdayClose
	p.fieldMap["tuesdayOpen"] = p.TuesdayOpen
	p.fieldMap["wednesdayClose"] = p.WednesdayClose
	p.fieldMap["wednesdayOpen"] = p.WednesdayOpen
}

func (p productService) clone(db *gorm.DB) productService {
	p.productServiceDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p productService) replaceDB(db *gorm.DB) productService {
	p.productServiceDo.ReplaceDB(db)
	return p
}

type productServiceDo struct{ gen.DO }

type IProductServiceDo interface {
	gen.SubQuery
	Debug() IProductServiceDo
	WithContext(ctx context.Context) IProductServiceDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IProductServiceDo
	WriteDB() IProductServiceDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IProductServiceDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IProductServiceDo
	Not(conds ...gen.Condition) IProductServiceDo
	Or(conds ...gen.Condition) IProductServiceDo
	Select(conds ...field.Expr) IProductServiceDo
	Where(conds ...gen.Condition) IProductServiceDo
	Order(conds ...field.Expr) IProductServiceDo
	Distinct(cols ...field.Expr) IProductServiceDo
	Omit(cols ...field.Expr) IProductServiceDo
	Join(table schema.Tabler, on ...field.Expr) IProductServiceDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IProductServiceDo
	RightJoin(table schema.Tabler, on ...field.Expr) IProductServiceDo
	Group(cols ...field.Expr) IProductServiceDo
	Having(conds ...gen.Condition) IProductServiceDo
	Limit(limit int) IProductServiceDo
	Offset(offset int) IProductServiceDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IProductServiceDo
	Unscoped() IProductServiceDo
	Create(values ...*model.ProductService) error
	CreateInBatches(values []*model.ProductService, batchSize int) error
	Save(values ...*model.ProductService) error
	First() (*model.ProductService, error)
	Take() (*model.ProductService, error)
	Last() (*model.ProductService, error)
	Find() ([]*model.ProductService, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ProductService, err error)
	FindInBatches(result *[]*model.ProductService, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ProductService) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IProductServiceDo
	Assign(attrs ...field.AssignExpr) IProductServiceDo
	Joins(fields ...field.RelationField) IProductServiceDo
	Preload(fields ...field.RelationField) IProductServiceDo
	FirstOrInit() (*model.ProductService, error)
	FirstOrCreate() (*model.ProductService, error)
	FindByPage(offset int, limit int) (result []*model.ProductService, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IProductServiceDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p productServiceDo) Debug() IProductServiceDo {
	return p.withDO(p.DO.Debug())
}

func (p productServiceDo) WithContext(ctx context.Context) IProductServiceDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p productServiceDo) ReadDB() IProductServiceDo {
	return p.Clauses(dbresolver.Read)
}

func (p productServiceDo) WriteDB() IProductServiceDo {
	return p.Clauses(dbresolver.Write)
}

func (p productServiceDo) Session(config *gorm.Session) IProductServiceDo {
	return p.withDO(p.DO.Session(config))
}

func (p productServiceDo) Clauses(conds ...clause.Expression) IProductServiceDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p productServiceDo) Returning(value interface{}, columns ...string) IProductServiceDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p productServiceDo) Not(conds ...gen.Condition) IProductServiceDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p productServiceDo) Or(conds ...gen.Condition) IProductServiceDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p productServiceDo) Select(conds ...field.Expr) IProductServiceDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p productServiceDo) Where(conds ...gen.Condition) IProductServiceDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p productServiceDo) Order(conds ...field.Expr) IProductServiceDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p productServiceDo) Distinct(cols ...field.Expr) IProductServiceDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p productServiceDo) Omit(cols ...field.Expr) IProductServiceDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p productServiceDo) Join(table schema.Tabler, on ...field.Expr) IProductServiceDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p productServiceDo) LeftJoin(table schema.Tabler, on ...field.Expr) IProductServiceDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p productServiceDo) RightJoin(table schema.Tabler, on ...field.Expr) IProductServiceDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p productServiceDo) Group(cols ...field.Expr) IProductServiceDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p productServiceDo) Having(conds ...gen.Condition) IProductServiceDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p productServiceDo) Limit(limit int) IProductServiceDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p productServiceDo) Offset(offset int) IProductServiceDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p productServiceDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IProductServiceDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p productServiceDo) Unscoped() IProductServiceDo {
	return p.withDO(p.DO.Unscoped())
}

func (p productServiceDo) Create(values ...*model.ProductService) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p productServiceDo) CreateInBatches(values []*model.ProductService, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p productServiceDo) Save(values ...*model.ProductService) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p productServiceDo) First() (*model.ProductService, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProductService), nil
	}
}

func (p productServiceDo) Take() (*model.ProductService, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProductService), nil
	}
}

func (p productServiceDo) Last() (*model.ProductService, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProductService), nil
	}
}

func (p productServiceDo) Find() ([]*model.ProductService, error) {
	result, err := p.DO.Find()
	return result.([]*model.ProductService), err
}

func (p productServiceDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ProductService, err error) {
	buf := make([]*model.ProductService, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p productServiceDo) FindInBatches(result *[]*model.ProductService, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p productServiceDo) Attrs(attrs ...field.AssignExpr) IProductServiceDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p productServiceDo) Assign(attrs ...field.AssignExpr) IProductServiceDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p productServiceDo) Joins(fields ...field.RelationField) IProductServiceDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p productServiceDo) Preload(fields ...field.RelationField) IProductServiceDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p productServiceDo) FirstOrInit() (*model.ProductService, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProductService), nil
	}
}

func (p productServiceDo) FirstOrCreate() (*model.ProductService, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProductService), nil
	}
}

func (p productServiceDo) FindByPage(offset int, limit int) (result []*model.ProductService, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p productServiceDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p productServiceDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p productServiceDo) Delete(models ...*model.ProductService) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *productServiceDo) withDO(do gen.Dao) *productServiceDo {
	p.DO = *do.(*gen.DO)
	return p
}
