// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend_go/model"
)

func newProductMedium(db *gorm.DB, opts ...gen.DOOption) productMedium {
	_productMedium := productMedium{}

	_productMedium.productMediumDo.UseDB(db, opts...)
	_productMedium.productMediumDo.UseModel(&model.ProductMedium{})

	tableName := _productMedium.productMediumDo.TableName()
	_productMedium.ALL = field.NewAsterisk(tableName)
	_productMedium.ID = field.NewString(tableName, "id")
	_productMedium.ProductID = field.NewString(tableName, "productId")
	_productMedium.URL = field.NewString(tableName, "url")
	_productMedium.Type = field.NewString(tableName, "type")
	_productMedium.Source = field.NewString(tableName, "source")
	_productMedium.Alt = field.NewString(tableName, "alt")
	_productMedium.Order_ = field.NewInt32(tableName, "order")
	_productMedium.ThumbnailURL = field.NewString(tableName, "thumbnailUrl")
	_productMedium.CreatedAt = field.NewTime(tableName, "createdAt")
	_productMedium.UpdatedAt = field.NewTime(tableName, "updatedAt")

	_productMedium.fillFieldMap()

	return _productMedium
}

type productMedium struct {
	productMediumDo

	ALL          field.Asterisk
	ID           field.String
	ProductID    field.String
	URL          field.String
	Type         field.String
	Source       field.String
	Alt          field.String
	Order_       field.Int32
	ThumbnailURL field.String
	CreatedAt    field.Time
	UpdatedAt    field.Time

	fieldMap map[string]field.Expr
}

func (p productMedium) Table(newTableName string) *productMedium {
	p.productMediumDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p productMedium) As(alias string) *productMedium {
	p.productMediumDo.DO = *(p.productMediumDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *productMedium) updateTableName(table string) *productMedium {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewString(table, "id")
	p.ProductID = field.NewString(table, "productId")
	p.URL = field.NewString(table, "url")
	p.Type = field.NewString(table, "type")
	p.Source = field.NewString(table, "source")
	p.Alt = field.NewString(table, "alt")
	p.Order_ = field.NewInt32(table, "order")
	p.ThumbnailURL = field.NewString(table, "thumbnailUrl")
	p.CreatedAt = field.NewTime(table, "createdAt")
	p.UpdatedAt = field.NewTime(table, "updatedAt")

	p.fillFieldMap()

	return p
}

func (p *productMedium) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *productMedium) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 10)
	p.fieldMap["id"] = p.ID
	p.fieldMap["productId"] = p.ProductID
	p.fieldMap["url"] = p.URL
	p.fieldMap["type"] = p.Type
	p.fieldMap["source"] = p.Source
	p.fieldMap["alt"] = p.Alt
	p.fieldMap["order"] = p.Order_
	p.fieldMap["thumbnailUrl"] = p.ThumbnailURL
	p.fieldMap["createdAt"] = p.CreatedAt
	p.fieldMap["updatedAt"] = p.UpdatedAt
}

func (p productMedium) clone(db *gorm.DB) productMedium {
	p.productMediumDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p productMedium) replaceDB(db *gorm.DB) productMedium {
	p.productMediumDo.ReplaceDB(db)
	return p
}

type productMediumDo struct{ gen.DO }

type IProductMediumDo interface {
	gen.SubQuery
	Debug() IProductMediumDo
	WithContext(ctx context.Context) IProductMediumDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IProductMediumDo
	WriteDB() IProductMediumDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IProductMediumDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IProductMediumDo
	Not(conds ...gen.Condition) IProductMediumDo
	Or(conds ...gen.Condition) IProductMediumDo
	Select(conds ...field.Expr) IProductMediumDo
	Where(conds ...gen.Condition) IProductMediumDo
	Order(conds ...field.Expr) IProductMediumDo
	Distinct(cols ...field.Expr) IProductMediumDo
	Omit(cols ...field.Expr) IProductMediumDo
	Join(table schema.Tabler, on ...field.Expr) IProductMediumDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IProductMediumDo
	RightJoin(table schema.Tabler, on ...field.Expr) IProductMediumDo
	Group(cols ...field.Expr) IProductMediumDo
	Having(conds ...gen.Condition) IProductMediumDo
	Limit(limit int) IProductMediumDo
	Offset(offset int) IProductMediumDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IProductMediumDo
	Unscoped() IProductMediumDo
	Create(values ...*model.ProductMedium) error
	CreateInBatches(values []*model.ProductMedium, batchSize int) error
	Save(values ...*model.ProductMedium) error
	First() (*model.ProductMedium, error)
	Take() (*model.ProductMedium, error)
	Last() (*model.ProductMedium, error)
	Find() ([]*model.ProductMedium, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ProductMedium, err error)
	FindInBatches(result *[]*model.ProductMedium, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ProductMedium) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IProductMediumDo
	Assign(attrs ...field.AssignExpr) IProductMediumDo
	Joins(fields ...field.RelationField) IProductMediumDo
	Preload(fields ...field.RelationField) IProductMediumDo
	FirstOrInit() (*model.ProductMedium, error)
	FirstOrCreate() (*model.ProductMedium, error)
	FindByPage(offset int, limit int) (result []*model.ProductMedium, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IProductMediumDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p productMediumDo) Debug() IProductMediumDo {
	return p.withDO(p.DO.Debug())
}

func (p productMediumDo) WithContext(ctx context.Context) IProductMediumDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p productMediumDo) ReadDB() IProductMediumDo {
	return p.Clauses(dbresolver.Read)
}

func (p productMediumDo) WriteDB() IProductMediumDo {
	return p.Clauses(dbresolver.Write)
}

func (p productMediumDo) Session(config *gorm.Session) IProductMediumDo {
	return p.withDO(p.DO.Session(config))
}

func (p productMediumDo) Clauses(conds ...clause.Expression) IProductMediumDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p productMediumDo) Returning(value interface{}, columns ...string) IProductMediumDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p productMediumDo) Not(conds ...gen.Condition) IProductMediumDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p productMediumDo) Or(conds ...gen.Condition) IProductMediumDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p productMediumDo) Select(conds ...field.Expr) IProductMediumDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p productMediumDo) Where(conds ...gen.Condition) IProductMediumDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p productMediumDo) Order(conds ...field.Expr) IProductMediumDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p productMediumDo) Distinct(cols ...field.Expr) IProductMediumDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p productMediumDo) Omit(cols ...field.Expr) IProductMediumDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p productMediumDo) Join(table schema.Tabler, on ...field.Expr) IProductMediumDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p productMediumDo) LeftJoin(table schema.Tabler, on ...field.Expr) IProductMediumDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p productMediumDo) RightJoin(table schema.Tabler, on ...field.Expr) IProductMediumDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p productMediumDo) Group(cols ...field.Expr) IProductMediumDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p productMediumDo) Having(conds ...gen.Condition) IProductMediumDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p productMediumDo) Limit(limit int) IProductMediumDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p productMediumDo) Offset(offset int) IProductMediumDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p productMediumDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IProductMediumDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p productMediumDo) Unscoped() IProductMediumDo {
	return p.withDO(p.DO.Unscoped())
}

func (p productMediumDo) Create(values ...*model.ProductMedium) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p productMediumDo) CreateInBatches(values []*model.ProductMedium, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p productMediumDo) Save(values ...*model.ProductMedium) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p productMediumDo) First() (*model.ProductMedium, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProductMedium), nil
	}
}

func (p productMediumDo) Take() (*model.ProductMedium, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProductMedium), nil
	}
}

func (p productMediumDo) Last() (*model.ProductMedium, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProductMedium), nil
	}
}

func (p productMediumDo) Find() ([]*model.ProductMedium, error) {
	result, err := p.DO.Find()
	return result.([]*model.ProductMedium), err
}

func (p productMediumDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ProductMedium, err error) {
	buf := make([]*model.ProductMedium, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p productMediumDo) FindInBatches(result *[]*model.ProductMedium, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p productMediumDo) Attrs(attrs ...field.AssignExpr) IProductMediumDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p productMediumDo) Assign(attrs ...field.AssignExpr) IProductMediumDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p productMediumDo) Joins(fields ...field.RelationField) IProductMediumDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p productMediumDo) Preload(fields ...field.RelationField) IProductMediumDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p productMediumDo) FirstOrInit() (*model.ProductMedium, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProductMedium), nil
	}
}

func (p productMediumDo) FirstOrCreate() (*model.ProductMedium, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProductMedium), nil
	}
}

func (p productMediumDo) FindByPage(offset int, limit int) (result []*model.ProductMedium, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p productMediumDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p productMediumDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p productMediumDo) Delete(models ...*model.ProductMedium) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *productMediumDo) withDO(do gen.Dao) *productMediumDo {
	p.DO = *do.(*gen.DO)
	return p
}
