// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend_go/model"
)

func newProductTicket(db *gorm.DB, opts ...gen.DOOption) productTicket {
	_productTicket := productTicket{}

	_productTicket.productTicketDo.UseDB(db, opts...)
	_productTicket.productTicketDo.UseModel(&model.ProductTicket{})

	tableName := _productTicket.productTicketDo.TableName()
	_productTicket.ALL = field.NewAsterisk(tableName)
	_productTicket.ID = field.NewString(tableName, "id")
	_productTicket.ProductID = field.NewString(tableName, "productId")
	_productTicket.SellingPrice = field.NewFloat64(tableName, "sellingPrice")
	_productTicket.EventDate = field.NewTime(tableName, "eventDate")
	_productTicket.EventEndDate = field.NewTime(tableName, "eventEndDate")
	_productTicket.Venue = field.NewString(tableName, "venue")
	_productTicket.VenueAddress = field.NewString(tableName, "venueAddress")
	_productTicket.MapURL = field.NewString(tableName, "mapUrl")
	_productTicket.TotalQuota = field.NewInt32(tableName, "totalQuota")
	_productTicket.SoldCount = field.NewInt32(tableName, "soldCount")
	_productTicket.MaxPerOrder = field.NewInt32(tableName, "maxPerOrder")
	_productTicket.SaleStartDate = field.NewTime(tableName, "saleStartDate")
	_productTicket.SaleEndDate = field.NewTime(tableName, "saleEndDate")
	_productTicket.Terms = field.NewString(tableName, "terms")
	_productTicket.CreatedAt = field.NewTime(tableName, "createdAt")
	_productTicket.UpdatedAt = field.NewTime(tableName, "updatedAt")

	_productTicket.fillFieldMap()

	return _productTicket
}

type productTicket struct {
	productTicketDo

	ALL           field.Asterisk
	ID            field.String
	ProductID     field.String
	SellingPrice  field.Float64
	EventDate     field.Time
	EventEndDate  field.Time
	Venue         field.String
	VenueAddress  field.String
	MapURL        field.String
	TotalQuota    field.Int32
	SoldCount     field.Int32
	MaxPerOrder   field.Int32
	SaleStartDate field.Time
	SaleEndDate   field.Time
	Terms         field.String
	CreatedAt     field.Time
	UpdatedAt     field.Time

	fieldMap map[string]field.Expr
}

func (p productTicket) Table(newTableName string) *productTicket {
	p.productTicketDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p productTicket) As(alias string) *productTicket {
	p.productTicketDo.DO = *(p.productTicketDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *productTicket) updateTableName(table string) *productTicket {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewString(table, "id")
	p.ProductID = field.NewString(table, "productId")
	p.SellingPrice = field.NewFloat64(table, "sellingPrice")
	p.EventDate = field.NewTime(table, "eventDate")
	p.EventEndDate = field.NewTime(table, "eventEndDate")
	p.Venue = field.NewString(table, "venue")
	p.VenueAddress = field.NewString(table, "venueAddress")
	p.MapURL = field.NewString(table, "mapUrl")
	p.TotalQuota = field.NewInt32(table, "totalQuota")
	p.SoldCount = field.NewInt32(table, "soldCount")
	p.MaxPerOrder = field.NewInt32(table, "maxPerOrder")
	p.SaleStartDate = field.NewTime(table, "saleStartDate")
	p.SaleEndDate = field.NewTime(table, "saleEndDate")
	p.Terms = field.NewString(table, "terms")
	p.CreatedAt = field.NewTime(table, "createdAt")
	p.UpdatedAt = field.NewTime(table, "updatedAt")

	p.fillFieldMap()

	return p
}

func (p *productTicket) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *productTicket) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 16)
	p.fieldMap["id"] = p.ID
	p.fieldMap["productId"] = p.ProductID
	p.fieldMap["sellingPrice"] = p.SellingPrice
	p.fieldMap["eventDate"] = p.EventDate
	p.fieldMap["eventEndDate"] = p.EventEndDate
	p.fieldMap["venue"] = p.Venue
	p.fieldMap["venueAddress"] = p.VenueAddress
	p.fieldMap["mapUrl"] = p.MapURL
	p.fieldMap["totalQuota"] = p.TotalQuota
	p.fieldMap["soldCount"] = p.SoldCount
	p.fieldMap["maxPerOrder"] = p.MaxPerOrder
	p.fieldMap["saleStartDate"] = p.SaleStartDate
	p.fieldMap["saleEndDate"] = p.SaleEndDate
	p.fieldMap["terms"] = p.Terms
	p.fieldMap["createdAt"] = p.CreatedAt
	p.fieldMap["updatedAt"] = p.UpdatedAt
}

func (p productTicket) clone(db *gorm.DB) productTicket {
	p.productTicketDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p productTicket) replaceDB(db *gorm.DB) productTicket {
	p.productTicketDo.ReplaceDB(db)
	return p
}

type productTicketDo struct{ gen.DO }

type IProductTicketDo interface {
	gen.SubQuery
	Debug() IProductTicketDo
	WithContext(ctx context.Context) IProductTicketDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IProductTicketDo
	WriteDB() IProductTicketDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IProductTicketDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IProductTicketDo
	Not(conds ...gen.Condition) IProductTicketDo
	Or(conds ...gen.Condition) IProductTicketDo
	Select(conds ...field.Expr) IProductTicketDo
	Where(conds ...gen.Condition) IProductTicketDo
	Order(conds ...field.Expr) IProductTicketDo
	Distinct(cols ...field.Expr) IProductTicketDo
	Omit(cols ...field.Expr) IProductTicketDo
	Join(table schema.Tabler, on ...field.Expr) IProductTicketDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IProductTicketDo
	RightJoin(table schema.Tabler, on ...field.Expr) IProductTicketDo
	Group(cols ...field.Expr) IProductTicketDo
	Having(conds ...gen.Condition) IProductTicketDo
	Limit(limit int) IProductTicketDo
	Offset(offset int) IProductTicketDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IProductTicketDo
	Unscoped() IProductTicketDo
	Create(values ...*model.ProductTicket) error
	CreateInBatches(values []*model.ProductTicket, batchSize int) error
	Save(values ...*model.ProductTicket) error
	First() (*model.ProductTicket, error)
	Take() (*model.ProductTicket, error)
	Last() (*model.ProductTicket, error)
	Find() ([]*model.ProductTicket, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ProductTicket, err error)
	FindInBatches(result *[]*model.ProductTicket, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ProductTicket) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IProductTicketDo
	Assign(attrs ...field.AssignExpr) IProductTicketDo
	Joins(fields ...field.RelationField) IProductTicketDo
	Preload(fields ...field.RelationField) IProductTicketDo
	FirstOrInit() (*model.ProductTicket, error)
	FirstOrCreate() (*model.ProductTicket, error)
	FindByPage(offset int, limit int) (result []*model.ProductTicket, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IProductTicketDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p productTicketDo) Debug() IProductTicketDo {
	return p.withDO(p.DO.Debug())
}

func (p productTicketDo) WithContext(ctx context.Context) IProductTicketDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p productTicketDo) ReadDB() IProductTicketDo {
	return p.Clauses(dbresolver.Read)
}

func (p productTicketDo) WriteDB() IProductTicketDo {
	return p.Clauses(dbresolver.Write)
}

func (p productTicketDo) Session(config *gorm.Session) IProductTicketDo {
	return p.withDO(p.DO.Session(config))
}

func (p productTicketDo) Clauses(conds ...clause.Expression) IProductTicketDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p productTicketDo) Returning(value interface{}, columns ...string) IProductTicketDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p productTicketDo) Not(conds ...gen.Condition) IProductTicketDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p productTicketDo) Or(conds ...gen.Condition) IProductTicketDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p productTicketDo) Select(conds ...field.Expr) IProductTicketDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p productTicketDo) Where(conds ...gen.Condition) IProductTicketDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p productTicketDo) Order(conds ...field.Expr) IProductTicketDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p productTicketDo) Distinct(cols ...field.Expr) IProductTicketDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p productTicketDo) Omit(cols ...field.Expr) IProductTicketDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p productTicketDo) Join(table schema.Tabler, on ...field.Expr) IProductTicketDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p productTicketDo) LeftJoin(table schema.Tabler, on ...field.Expr) IProductTicketDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p productTicketDo) RightJoin(table schema.Tabler, on ...field.Expr) IProductTicketDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p productTicketDo) Group(cols ...field.Expr) IProductTicketDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p productTicketDo) Having(conds ...gen.Condition) IProductTicketDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p productTicketDo) Limit(limit int) IProductTicketDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p productTicketDo) Offset(offset int) IProductTicketDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p productTicketDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IProductTicketDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p productTicketDo) Unscoped() IProductTicketDo {
	return p.withDO(p.DO.Unscoped())
}

func (p productTicketDo) Create(values ...*model.ProductTicket) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p productTicketDo) CreateInBatches(values []*model.ProductTicket, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p productTicketDo) Save(values ...*model.ProductTicket) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p productTicketDo) First() (*model.ProductTicket, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProductTicket), nil
	}
}

func (p productTicketDo) Take() (*model.ProductTicket, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProductTicket), nil
	}
}

func (p productTicketDo) Last() (*model.ProductTicket, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProductTicket), nil
	}
}

func (p productTicketDo) Find() ([]*model.ProductTicket, error) {
	result, err := p.DO.Find()
	return result.([]*model.ProductTicket), err
}

func (p productTicketDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ProductTicket, err error) {
	buf := make([]*model.ProductTicket, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p productTicketDo) FindInBatches(result *[]*model.ProductTicket, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p productTicketDo) Attrs(attrs ...field.AssignExpr) IProductTicketDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p productTicketDo) Assign(attrs ...field.AssignExpr) IProductTicketDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p productTicketDo) Joins(fields ...field.RelationField) IProductTicketDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p productTicketDo) Preload(fields ...field.RelationField) IProductTicketDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p productTicketDo) FirstOrInit() (*model.ProductTicket, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProductTicket), nil
	}
}

func (p productTicketDo) FirstOrCreate() (*model.ProductTicket, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProductTicket), nil
	}
}

func (p productTicketDo) FindByPage(offset int, limit int) (result []*model.ProductTicket, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p productTicketDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p productTicketDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p productTicketDo) Delete(models ...*model.ProductTicket) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *productTicketDo) withDO(do gen.Dao) *productTicketDo {
	p.DO = *do.(*gen.DO)
	return p
}
