// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend_go/model"
)

func newProductGood(db *gorm.DB, opts ...gen.DOOption) productGood {
	_productGood := productGood{}

	_productGood.productGoodDo.UseDB(db, opts...)
	_productGood.productGoodDo.UseModel(&model.ProductGood{})

	tableName := _productGood.productGoodDo.TableName()
	_productGood.ALL = field.NewAsterisk(tableName)
	_productGood.ID = field.NewString(tableName, "id")
	_productGood.ProductID = field.NewString(tableName, "productId")
	_productGood.CurrentStock = field.NewInt32(tableName, "currentStock")
	_productGood.MinStock = field.NewInt32(tableName, "minStock")
	_productGood.Unit = field.NewString(tableName, "unit")
	_productGood.AverageHpp = field.NewFloat64(tableName, "averageHpp")
	_productGood.SellingPrice = field.NewFloat64(tableName, "sellingPrice")
	_productGood.CreatedAt = field.NewTime(tableName, "createdAt")
	_productGood.UpdatedAt = field.NewTime(tableName, "updatedAt")
	_productGood.MaxStock = field.NewInt32(tableName, "maxStock")

	_productGood.fillFieldMap()

	return _productGood
}

type productGood struct {
	productGoodDo

	ALL          field.Asterisk
	ID           field.String
	ProductID    field.String
	CurrentStock field.Int32
	MinStock     field.Int32
	Unit         field.String
	AverageHpp   field.Float64
	SellingPrice field.Float64
	CreatedAt    field.Time
	UpdatedAt    field.Time
	MaxStock     field.Int32

	fieldMap map[string]field.Expr
}

func (p productGood) Table(newTableName string) *productGood {
	p.productGoodDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p productGood) As(alias string) *productGood {
	p.productGoodDo.DO = *(p.productGoodDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *productGood) updateTableName(table string) *productGood {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewString(table, "id")
	p.ProductID = field.NewString(table, "productId")
	p.CurrentStock = field.NewInt32(table, "currentStock")
	p.MinStock = field.NewInt32(table, "minStock")
	p.Unit = field.NewString(table, "unit")
	p.AverageHpp = field.NewFloat64(table, "averageHpp")
	p.SellingPrice = field.NewFloat64(table, "sellingPrice")
	p.CreatedAt = field.NewTime(table, "createdAt")
	p.UpdatedAt = field.NewTime(table, "updatedAt")
	p.MaxStock = field.NewInt32(table, "maxStock")

	p.fillFieldMap()

	return p
}

func (p *productGood) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *productGood) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 10)
	p.fieldMap["id"] = p.ID
	p.fieldMap["productId"] = p.ProductID
	p.fieldMap["currentStock"] = p.CurrentStock
	p.fieldMap["minStock"] = p.MinStock
	p.fieldMap["unit"] = p.Unit
	p.fieldMap["averageHpp"] = p.AverageHpp
	p.fieldMap["sellingPrice"] = p.SellingPrice
	p.fieldMap["createdAt"] = p.CreatedAt
	p.fieldMap["updatedAt"] = p.UpdatedAt
	p.fieldMap["maxStock"] = p.MaxStock
}

func (p productGood) clone(db *gorm.DB) productGood {
	p.productGoodDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p productGood) replaceDB(db *gorm.DB) productGood {
	p.productGoodDo.ReplaceDB(db)
	return p
}

type productGoodDo struct{ gen.DO }

type IProductGoodDo interface {
	gen.SubQuery
	Debug() IProductGoodDo
	WithContext(ctx context.Context) IProductGoodDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IProductGoodDo
	WriteDB() IProductGoodDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IProductGoodDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IProductGoodDo
	Not(conds ...gen.Condition) IProductGoodDo
	Or(conds ...gen.Condition) IProductGoodDo
	Select(conds ...field.Expr) IProductGoodDo
	Where(conds ...gen.Condition) IProductGoodDo
	Order(conds ...field.Expr) IProductGoodDo
	Distinct(cols ...field.Expr) IProductGoodDo
	Omit(cols ...field.Expr) IProductGoodDo
	Join(table schema.Tabler, on ...field.Expr) IProductGoodDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IProductGoodDo
	RightJoin(table schema.Tabler, on ...field.Expr) IProductGoodDo
	Group(cols ...field.Expr) IProductGoodDo
	Having(conds ...gen.Condition) IProductGoodDo
	Limit(limit int) IProductGoodDo
	Offset(offset int) IProductGoodDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IProductGoodDo
	Unscoped() IProductGoodDo
	Create(values ...*model.ProductGood) error
	CreateInBatches(values []*model.ProductGood, batchSize int) error
	Save(values ...*model.ProductGood) error
	First() (*model.ProductGood, error)
	Take() (*model.ProductGood, error)
	Last() (*model.ProductGood, error)
	Find() ([]*model.ProductGood, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ProductGood, err error)
	FindInBatches(result *[]*model.ProductGood, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ProductGood) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IProductGoodDo
	Assign(attrs ...field.AssignExpr) IProductGoodDo
	Joins(fields ...field.RelationField) IProductGoodDo
	Preload(fields ...field.RelationField) IProductGoodDo
	FirstOrInit() (*model.ProductGood, error)
	FirstOrCreate() (*model.ProductGood, error)
	FindByPage(offset int, limit int) (result []*model.ProductGood, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IProductGoodDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p productGoodDo) Debug() IProductGoodDo {
	return p.withDO(p.DO.Debug())
}

func (p productGoodDo) WithContext(ctx context.Context) IProductGoodDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p productGoodDo) ReadDB() IProductGoodDo {
	return p.Clauses(dbresolver.Read)
}

func (p productGoodDo) WriteDB() IProductGoodDo {
	return p.Clauses(dbresolver.Write)
}

func (p productGoodDo) Session(config *gorm.Session) IProductGoodDo {
	return p.withDO(p.DO.Session(config))
}

func (p productGoodDo) Clauses(conds ...clause.Expression) IProductGoodDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p productGoodDo) Returning(value interface{}, columns ...string) IProductGoodDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p productGoodDo) Not(conds ...gen.Condition) IProductGoodDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p productGoodDo) Or(conds ...gen.Condition) IProductGoodDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p productGoodDo) Select(conds ...field.Expr) IProductGoodDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p productGoodDo) Where(conds ...gen.Condition) IProductGoodDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p productGoodDo) Order(conds ...field.Expr) IProductGoodDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p productGoodDo) Distinct(cols ...field.Expr) IProductGoodDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p productGoodDo) Omit(cols ...field.Expr) IProductGoodDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p productGoodDo) Join(table schema.Tabler, on ...field.Expr) IProductGoodDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p productGoodDo) LeftJoin(table schema.Tabler, on ...field.Expr) IProductGoodDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p productGoodDo) RightJoin(table schema.Tabler, on ...field.Expr) IProductGoodDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p productGoodDo) Group(cols ...field.Expr) IProductGoodDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p productGoodDo) Having(conds ...gen.Condition) IProductGoodDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p productGoodDo) Limit(limit int) IProductGoodDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p productGoodDo) Offset(offset int) IProductGoodDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p productGoodDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IProductGoodDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p productGoodDo) Unscoped() IProductGoodDo {
	return p.withDO(p.DO.Unscoped())
}

func (p productGoodDo) Create(values ...*model.ProductGood) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p productGoodDo) CreateInBatches(values []*model.ProductGood, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p productGoodDo) Save(values ...*model.ProductGood) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p productGoodDo) First() (*model.ProductGood, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProductGood), nil
	}
}

func (p productGoodDo) Take() (*model.ProductGood, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProductGood), nil
	}
}

func (p productGoodDo) Last() (*model.ProductGood, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProductGood), nil
	}
}

func (p productGoodDo) Find() ([]*model.ProductGood, error) {
	result, err := p.DO.Find()
	return result.([]*model.ProductGood), err
}

func (p productGoodDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ProductGood, err error) {
	buf := make([]*model.ProductGood, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p productGoodDo) FindInBatches(result *[]*model.ProductGood, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p productGoodDo) Attrs(attrs ...field.AssignExpr) IProductGoodDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p productGoodDo) Assign(attrs ...field.AssignExpr) IProductGoodDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p productGoodDo) Joins(fields ...field.RelationField) IProductGoodDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p productGoodDo) Preload(fields ...field.RelationField) IProductGoodDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p productGoodDo) FirstOrInit() (*model.ProductGood, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProductGood), nil
	}
}

func (p productGoodDo) FirstOrCreate() (*model.ProductGood, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProductGood), nil
	}
}

func (p productGoodDo) FindByPage(offset int, limit int) (result []*model.ProductGood, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p productGoodDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p productGoodDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p productGoodDo) Delete(models ...*model.ProductGood) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *productGoodDo) withDO(do gen.Dao) *productGoodDo {
	p.DO = *do.(*gen.DO)
	return p
}
