// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend_go/model"
)

func newReceiptSetting(db *gorm.DB, opts ...gen.DOOption) receiptSetting {
	_receiptSetting := receiptSetting{}

	_receiptSetting.receiptSettingDo.UseDB(db, opts...)
	_receiptSetting.receiptSettingDo.UseModel(&model.ReceiptSetting{})

	tableName := _receiptSetting.receiptSettingDo.TableName()
	_receiptSetting.ALL = field.NewAsterisk(tableName)
	_receiptSetting.ID = field.NewString(tableName, "id")
	_receiptSetting.OutletID = field.NewString(tableName, "outletId")
	_receiptSetting.PhotoString = field.NewString(tableName, "photoString")
	_receiptSetting.ShowLogo = field.NewBool(tableName, "showLogo")
	_receiptSetting.PrintHeight = field.NewString(tableName, "printHeight")
	_receiptSetting.PrintWidth = field.NewString(tableName, "printWidth")

	_receiptSetting.fillFieldMap()

	return _receiptSetting
}

type receiptSetting struct {
	receiptSettingDo

	ALL         field.Asterisk
	ID          field.String
	OutletID    field.String
	PhotoString field.String
	ShowLogo    field.Bool
	PrintHeight field.String
	PrintWidth  field.String

	fieldMap map[string]field.Expr
}

func (r receiptSetting) Table(newTableName string) *receiptSetting {
	r.receiptSettingDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r receiptSetting) As(alias string) *receiptSetting {
	r.receiptSettingDo.DO = *(r.receiptSettingDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *receiptSetting) updateTableName(table string) *receiptSetting {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewString(table, "id")
	r.OutletID = field.NewString(table, "outletId")
	r.PhotoString = field.NewString(table, "photoString")
	r.ShowLogo = field.NewBool(table, "showLogo")
	r.PrintHeight = field.NewString(table, "printHeight")
	r.PrintWidth = field.NewString(table, "printWidth")

	r.fillFieldMap()

	return r
}

func (r *receiptSetting) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *receiptSetting) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 6)
	r.fieldMap["id"] = r.ID
	r.fieldMap["outletId"] = r.OutletID
	r.fieldMap["photoString"] = r.PhotoString
	r.fieldMap["showLogo"] = r.ShowLogo
	r.fieldMap["printHeight"] = r.PrintHeight
	r.fieldMap["printWidth"] = r.PrintWidth
}

func (r receiptSetting) clone(db *gorm.DB) receiptSetting {
	r.receiptSettingDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r receiptSetting) replaceDB(db *gorm.DB) receiptSetting {
	r.receiptSettingDo.ReplaceDB(db)
	return r
}

type receiptSettingDo struct{ gen.DO }

type IReceiptSettingDo interface {
	gen.SubQuery
	Debug() IReceiptSettingDo
	WithContext(ctx context.Context) IReceiptSettingDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IReceiptSettingDo
	WriteDB() IReceiptSettingDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IReceiptSettingDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IReceiptSettingDo
	Not(conds ...gen.Condition) IReceiptSettingDo
	Or(conds ...gen.Condition) IReceiptSettingDo
	Select(conds ...field.Expr) IReceiptSettingDo
	Where(conds ...gen.Condition) IReceiptSettingDo
	Order(conds ...field.Expr) IReceiptSettingDo
	Distinct(cols ...field.Expr) IReceiptSettingDo
	Omit(cols ...field.Expr) IReceiptSettingDo
	Join(table schema.Tabler, on ...field.Expr) IReceiptSettingDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IReceiptSettingDo
	RightJoin(table schema.Tabler, on ...field.Expr) IReceiptSettingDo
	Group(cols ...field.Expr) IReceiptSettingDo
	Having(conds ...gen.Condition) IReceiptSettingDo
	Limit(limit int) IReceiptSettingDo
	Offset(offset int) IReceiptSettingDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IReceiptSettingDo
	Unscoped() IReceiptSettingDo
	Create(values ...*model.ReceiptSetting) error
	CreateInBatches(values []*model.ReceiptSetting, batchSize int) error
	Save(values ...*model.ReceiptSetting) error
	First() (*model.ReceiptSetting, error)
	Take() (*model.ReceiptSetting, error)
	Last() (*model.ReceiptSetting, error)
	Find() ([]*model.ReceiptSetting, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ReceiptSetting, err error)
	FindInBatches(result *[]*model.ReceiptSetting, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ReceiptSetting) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IReceiptSettingDo
	Assign(attrs ...field.AssignExpr) IReceiptSettingDo
	Joins(fields ...field.RelationField) IReceiptSettingDo
	Preload(fields ...field.RelationField) IReceiptSettingDo
	FirstOrInit() (*model.ReceiptSetting, error)
	FirstOrCreate() (*model.ReceiptSetting, error)
	FindByPage(offset int, limit int) (result []*model.ReceiptSetting, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IReceiptSettingDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r receiptSettingDo) Debug() IReceiptSettingDo {
	return r.withDO(r.DO.Debug())
}

func (r receiptSettingDo) WithContext(ctx context.Context) IReceiptSettingDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r receiptSettingDo) ReadDB() IReceiptSettingDo {
	return r.Clauses(dbresolver.Read)
}

func (r receiptSettingDo) WriteDB() IReceiptSettingDo {
	return r.Clauses(dbresolver.Write)
}

func (r receiptSettingDo) Session(config *gorm.Session) IReceiptSettingDo {
	return r.withDO(r.DO.Session(config))
}

func (r receiptSettingDo) Clauses(conds ...clause.Expression) IReceiptSettingDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r receiptSettingDo) Returning(value interface{}, columns ...string) IReceiptSettingDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r receiptSettingDo) Not(conds ...gen.Condition) IReceiptSettingDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r receiptSettingDo) Or(conds ...gen.Condition) IReceiptSettingDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r receiptSettingDo) Select(conds ...field.Expr) IReceiptSettingDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r receiptSettingDo) Where(conds ...gen.Condition) IReceiptSettingDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r receiptSettingDo) Order(conds ...field.Expr) IReceiptSettingDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r receiptSettingDo) Distinct(cols ...field.Expr) IReceiptSettingDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r receiptSettingDo) Omit(cols ...field.Expr) IReceiptSettingDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r receiptSettingDo) Join(table schema.Tabler, on ...field.Expr) IReceiptSettingDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r receiptSettingDo) LeftJoin(table schema.Tabler, on ...field.Expr) IReceiptSettingDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r receiptSettingDo) RightJoin(table schema.Tabler, on ...field.Expr) IReceiptSettingDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r receiptSettingDo) Group(cols ...field.Expr) IReceiptSettingDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r receiptSettingDo) Having(conds ...gen.Condition) IReceiptSettingDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r receiptSettingDo) Limit(limit int) IReceiptSettingDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r receiptSettingDo) Offset(offset int) IReceiptSettingDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r receiptSettingDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IReceiptSettingDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r receiptSettingDo) Unscoped() IReceiptSettingDo {
	return r.withDO(r.DO.Unscoped())
}

func (r receiptSettingDo) Create(values ...*model.ReceiptSetting) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r receiptSettingDo) CreateInBatches(values []*model.ReceiptSetting, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r receiptSettingDo) Save(values ...*model.ReceiptSetting) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r receiptSettingDo) First() (*model.ReceiptSetting, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ReceiptSetting), nil
	}
}

func (r receiptSettingDo) Take() (*model.ReceiptSetting, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ReceiptSetting), nil
	}
}

func (r receiptSettingDo) Last() (*model.ReceiptSetting, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ReceiptSetting), nil
	}
}

func (r receiptSettingDo) Find() ([]*model.ReceiptSetting, error) {
	result, err := r.DO.Find()
	return result.([]*model.ReceiptSetting), err
}

func (r receiptSettingDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ReceiptSetting, err error) {
	buf := make([]*model.ReceiptSetting, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r receiptSettingDo) FindInBatches(result *[]*model.ReceiptSetting, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r receiptSettingDo) Attrs(attrs ...field.AssignExpr) IReceiptSettingDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r receiptSettingDo) Assign(attrs ...field.AssignExpr) IReceiptSettingDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r receiptSettingDo) Joins(fields ...field.RelationField) IReceiptSettingDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r receiptSettingDo) Preload(fields ...field.RelationField) IReceiptSettingDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r receiptSettingDo) FirstOrInit() (*model.ReceiptSetting, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ReceiptSetting), nil
	}
}

func (r receiptSettingDo) FirstOrCreate() (*model.ReceiptSetting, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ReceiptSetting), nil
	}
}

func (r receiptSettingDo) FindByPage(offset int, limit int) (result []*model.ReceiptSetting, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r receiptSettingDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r receiptSettingDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r receiptSettingDo) Delete(models ...*model.ReceiptSetting) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *receiptSettingDo) withDO(do gen.Dao) *receiptSettingDo {
	r.DO = *do.(*gen.DO)
	return r
}
