// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend_go/model"
)

func newSubscriptionInvoice(db *gorm.DB, opts ...gen.DOOption) subscriptionInvoice {
	_subscriptionInvoice := subscriptionInvoice{}

	_subscriptionInvoice.subscriptionInvoiceDo.UseDB(db, opts...)
	_subscriptionInvoice.subscriptionInvoiceDo.UseModel(&model.SubscriptionInvoice{})

	tableName := _subscriptionInvoice.subscriptionInvoiceDo.TableName()
	_subscriptionInvoice.ALL = field.NewAsterisk(tableName)
	_subscriptionInvoice.ID = field.NewString(tableName, "id")
	_subscriptionInvoice.InvoiceNumber = field.NewString(tableName, "invoiceNumber")
	_subscriptionInvoice.Amount = field.NewFloat64(tableName, "amount")
	_subscriptionInvoice.Status = field.NewString(tableName, "status")
	_subscriptionInvoice.PaymentURL = field.NewString(tableName, "paymentUrl")
	_subscriptionInvoice.ExternalID = field.NewString(tableName, "externalId")
	_subscriptionInvoice.ProofImage = field.NewString(tableName, "proofImage")
	_subscriptionInvoice.VerifiedAt = field.NewTime(tableName, "verifiedAt")
	_subscriptionInvoice.RejectionReason = field.NewString(tableName, "rejectionReason")
	_subscriptionInvoice.PaidAt = field.NewTime(tableName, "paidAt")
	_subscriptionInvoice.BusinessID = field.NewString(tableName, "businessId")
	_subscriptionInvoice.SubscriptionID = field.NewString(tableName, "subscriptionId")
	_subscriptionInvoice.CreatedAt = field.NewTime(tableName, "createdAt")
	_subscriptionInvoice.UpdatedAt = field.NewTime(tableName, "updatedAt")
	_subscriptionInvoice.ProofUploadedAt = field.NewTime(tableName, "proofUploadedAt")

	_subscriptionInvoice.fillFieldMap()

	return _subscriptionInvoice
}

type subscriptionInvoice struct {
	subscriptionInvoiceDo

	ALL             field.Asterisk
	ID              field.String
	InvoiceNumber   field.String
	Amount          field.Float64
	Status          field.String
	PaymentURL      field.String
	ExternalID      field.String
	ProofImage      field.String
	VerifiedAt      field.Time
	RejectionReason field.String
	PaidAt          field.Time
	BusinessID      field.String
	SubscriptionID  field.String
	CreatedAt       field.Time
	UpdatedAt       field.Time
	ProofUploadedAt field.Time

	fieldMap map[string]field.Expr
}

func (s subscriptionInvoice) Table(newTableName string) *subscriptionInvoice {
	s.subscriptionInvoiceDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s subscriptionInvoice) As(alias string) *subscriptionInvoice {
	s.subscriptionInvoiceDo.DO = *(s.subscriptionInvoiceDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *subscriptionInvoice) updateTableName(table string) *subscriptionInvoice {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewString(table, "id")
	s.InvoiceNumber = field.NewString(table, "invoiceNumber")
	s.Amount = field.NewFloat64(table, "amount")
	s.Status = field.NewString(table, "status")
	s.PaymentURL = field.NewString(table, "paymentUrl")
	s.ExternalID = field.NewString(table, "externalId")
	s.ProofImage = field.NewString(table, "proofImage")
	s.VerifiedAt = field.NewTime(table, "verifiedAt")
	s.RejectionReason = field.NewString(table, "rejectionReason")
	s.PaidAt = field.NewTime(table, "paidAt")
	s.BusinessID = field.NewString(table, "businessId")
	s.SubscriptionID = field.NewString(table, "subscriptionId")
	s.CreatedAt = field.NewTime(table, "createdAt")
	s.UpdatedAt = field.NewTime(table, "updatedAt")
	s.ProofUploadedAt = field.NewTime(table, "proofUploadedAt")

	s.fillFieldMap()

	return s
}

func (s *subscriptionInvoice) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *subscriptionInvoice) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 15)
	s.fieldMap["id"] = s.ID
	s.fieldMap["invoiceNumber"] = s.InvoiceNumber
	s.fieldMap["amount"] = s.Amount
	s.fieldMap["status"] = s.Status
	s.fieldMap["paymentUrl"] = s.PaymentURL
	s.fieldMap["externalId"] = s.ExternalID
	s.fieldMap["proofImage"] = s.ProofImage
	s.fieldMap["verifiedAt"] = s.VerifiedAt
	s.fieldMap["rejectionReason"] = s.RejectionReason
	s.fieldMap["paidAt"] = s.PaidAt
	s.fieldMap["businessId"] = s.BusinessID
	s.fieldMap["subscriptionId"] = s.SubscriptionID
	s.fieldMap["createdAt"] = s.CreatedAt
	s.fieldMap["updatedAt"] = s.UpdatedAt
	s.fieldMap["proofUploadedAt"] = s.ProofUploadedAt
}

func (s subscriptionInvoice) clone(db *gorm.DB) subscriptionInvoice {
	s.subscriptionInvoiceDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s subscriptionInvoice) replaceDB(db *gorm.DB) subscriptionInvoice {
	s.subscriptionInvoiceDo.ReplaceDB(db)
	return s
}

type subscriptionInvoiceDo struct{ gen.DO }

type ISubscriptionInvoiceDo interface {
	gen.SubQuery
	Debug() ISubscriptionInvoiceDo
	WithContext(ctx context.Context) ISubscriptionInvoiceDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISubscriptionInvoiceDo
	WriteDB() ISubscriptionInvoiceDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISubscriptionInvoiceDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISubscriptionInvoiceDo
	Not(conds ...gen.Condition) ISubscriptionInvoiceDo
	Or(conds ...gen.Condition) ISubscriptionInvoiceDo
	Select(conds ...field.Expr) ISubscriptionInvoiceDo
	Where(conds ...gen.Condition) ISubscriptionInvoiceDo
	Order(conds ...field.Expr) ISubscriptionInvoiceDo
	Distinct(cols ...field.Expr) ISubscriptionInvoiceDo
	Omit(cols ...field.Expr) ISubscriptionInvoiceDo
	Join(table schema.Tabler, on ...field.Expr) ISubscriptionInvoiceDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISubscriptionInvoiceDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISubscriptionInvoiceDo
	Group(cols ...field.Expr) ISubscriptionInvoiceDo
	Having(conds ...gen.Condition) ISubscriptionInvoiceDo
	Limit(limit int) ISubscriptionInvoiceDo
	Offset(offset int) ISubscriptionInvoiceDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISubscriptionInvoiceDo
	Unscoped() ISubscriptionInvoiceDo
	Create(values ...*model.SubscriptionInvoice) error
	CreateInBatches(values []*model.SubscriptionInvoice, batchSize int) error
	Save(values ...*model.SubscriptionInvoice) error
	First() (*model.SubscriptionInvoice, error)
	Take() (*model.SubscriptionInvoice, error)
	Last() (*model.SubscriptionInvoice, error)
	Find() ([]*model.SubscriptionInvoice, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SubscriptionInvoice, err error)
	FindInBatches(result *[]*model.SubscriptionInvoice, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SubscriptionInvoice) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISubscriptionInvoiceDo
	Assign(attrs ...field.AssignExpr) ISubscriptionInvoiceDo
	Joins(fields ...field.RelationField) ISubscriptionInvoiceDo
	Preload(fields ...field.RelationField) ISubscriptionInvoiceDo
	FirstOrInit() (*model.SubscriptionInvoice, error)
	FirstOrCreate() (*model.SubscriptionInvoice, error)
	FindByPage(offset int, limit int) (result []*model.SubscriptionInvoice, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISubscriptionInvoiceDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s subscriptionInvoiceDo) Debug() ISubscriptionInvoiceDo {
	return s.withDO(s.DO.Debug())
}

func (s subscriptionInvoiceDo) WithContext(ctx context.Context) ISubscriptionInvoiceDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s subscriptionInvoiceDo) ReadDB() ISubscriptionInvoiceDo {
	return s.Clauses(dbresolver.Read)
}

func (s subscriptionInvoiceDo) WriteDB() ISubscriptionInvoiceDo {
	return s.Clauses(dbresolver.Write)
}

func (s subscriptionInvoiceDo) Session(config *gorm.Session) ISubscriptionInvoiceDo {
	return s.withDO(s.DO.Session(config))
}

func (s subscriptionInvoiceDo) Clauses(conds ...clause.Expression) ISubscriptionInvoiceDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s subscriptionInvoiceDo) Returning(value interface{}, columns ...string) ISubscriptionInvoiceDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s subscriptionInvoiceDo) Not(conds ...gen.Condition) ISubscriptionInvoiceDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s subscriptionInvoiceDo) Or(conds ...gen.Condition) ISubscriptionInvoiceDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s subscriptionInvoiceDo) Select(conds ...field.Expr) ISubscriptionInvoiceDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s subscriptionInvoiceDo) Where(conds ...gen.Condition) ISubscriptionInvoiceDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s subscriptionInvoiceDo) Order(conds ...field.Expr) ISubscriptionInvoiceDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s subscriptionInvoiceDo) Distinct(cols ...field.Expr) ISubscriptionInvoiceDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s subscriptionInvoiceDo) Omit(cols ...field.Expr) ISubscriptionInvoiceDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s subscriptionInvoiceDo) Join(table schema.Tabler, on ...field.Expr) ISubscriptionInvoiceDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s subscriptionInvoiceDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISubscriptionInvoiceDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s subscriptionInvoiceDo) RightJoin(table schema.Tabler, on ...field.Expr) ISubscriptionInvoiceDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s subscriptionInvoiceDo) Group(cols ...field.Expr) ISubscriptionInvoiceDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s subscriptionInvoiceDo) Having(conds ...gen.Condition) ISubscriptionInvoiceDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s subscriptionInvoiceDo) Limit(limit int) ISubscriptionInvoiceDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s subscriptionInvoiceDo) Offset(offset int) ISubscriptionInvoiceDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s subscriptionInvoiceDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISubscriptionInvoiceDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s subscriptionInvoiceDo) Unscoped() ISubscriptionInvoiceDo {
	return s.withDO(s.DO.Unscoped())
}

func (s subscriptionInvoiceDo) Create(values ...*model.SubscriptionInvoice) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s subscriptionInvoiceDo) CreateInBatches(values []*model.SubscriptionInvoice, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s subscriptionInvoiceDo) Save(values ...*model.SubscriptionInvoice) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s subscriptionInvoiceDo) First() (*model.SubscriptionInvoice, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SubscriptionInvoice), nil
	}
}

func (s subscriptionInvoiceDo) Take() (*model.SubscriptionInvoice, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SubscriptionInvoice), nil
	}
}

func (s subscriptionInvoiceDo) Last() (*model.SubscriptionInvoice, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SubscriptionInvoice), nil
	}
}

func (s subscriptionInvoiceDo) Find() ([]*model.SubscriptionInvoice, error) {
	result, err := s.DO.Find()
	return result.([]*model.SubscriptionInvoice), err
}

func (s subscriptionInvoiceDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SubscriptionInvoice, err error) {
	buf := make([]*model.SubscriptionInvoice, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s subscriptionInvoiceDo) FindInBatches(result *[]*model.SubscriptionInvoice, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s subscriptionInvoiceDo) Attrs(attrs ...field.AssignExpr) ISubscriptionInvoiceDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s subscriptionInvoiceDo) Assign(attrs ...field.AssignExpr) ISubscriptionInvoiceDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s subscriptionInvoiceDo) Joins(fields ...field.RelationField) ISubscriptionInvoiceDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s subscriptionInvoiceDo) Preload(fields ...field.RelationField) ISubscriptionInvoiceDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s subscriptionInvoiceDo) FirstOrInit() (*model.SubscriptionInvoice, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SubscriptionInvoice), nil
	}
}

func (s subscriptionInvoiceDo) FirstOrCreate() (*model.SubscriptionInvoice, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SubscriptionInvoice), nil
	}
}

func (s subscriptionInvoiceDo) FindByPage(offset int, limit int) (result []*model.SubscriptionInvoice, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s subscriptionInvoiceDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s subscriptionInvoiceDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s subscriptionInvoiceDo) Delete(models ...*model.SubscriptionInvoice) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *subscriptionInvoiceDo) withDO(do gen.Dao) *subscriptionInvoiceDo {
	s.DO = *do.(*gen.DO)
	return s
}
