// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend_go/model"
)

func newTicketCode(db *gorm.DB, opts ...gen.DOOption) ticketCode {
	_ticketCode := ticketCode{}

	_ticketCode.ticketCodeDo.UseDB(db, opts...)
	_ticketCode.ticketCodeDo.UseModel(&model.TicketCode{})

	tableName := _ticketCode.ticketCodeDo.TableName()
	_ticketCode.ALL = field.NewAsterisk(tableName)
	_ticketCode.ID = field.NewString(tableName, "id")
	_ticketCode.Code = field.NewString(tableName, "code")
	_ticketCode.Status = field.NewString(tableName, "status")
	_ticketCode.OrderItemID = field.NewString(tableName, "orderItemId")
	_ticketCode.RedeemedAt = field.NewTime(tableName, "redeemedAt")
	_ticketCode.RedeemedByID = field.NewString(tableName, "redeemedById")
	_ticketCode.CreatedAt = field.NewTime(tableName, "createdAt")
	_ticketCode.UpdatedAt = field.NewTime(tableName, "updatedAt")

	_ticketCode.fillFieldMap()

	return _ticketCode
}

type ticketCode struct {
	ticketCodeDo

	ALL          field.Asterisk
	ID           field.String
	Code         field.String
	Status       field.String
	OrderItemID  field.String
	RedeemedAt   field.Time
	RedeemedByID field.String
	CreatedAt    field.Time
	UpdatedAt    field.Time

	fieldMap map[string]field.Expr
}

func (t ticketCode) Table(newTableName string) *ticketCode {
	t.ticketCodeDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t ticketCode) As(alias string) *ticketCode {
	t.ticketCodeDo.DO = *(t.ticketCodeDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *ticketCode) updateTableName(table string) *ticketCode {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewString(table, "id")
	t.Code = field.NewString(table, "code")
	t.Status = field.NewString(table, "status")
	t.OrderItemID = field.NewString(table, "orderItemId")
	t.RedeemedAt = field.NewTime(table, "redeemedAt")
	t.RedeemedByID = field.NewString(table, "redeemedById")
	t.CreatedAt = field.NewTime(table, "createdAt")
	t.UpdatedAt = field.NewTime(table, "updatedAt")

	t.fillFieldMap()

	return t
}

func (t *ticketCode) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *ticketCode) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 8)
	t.fieldMap["id"] = t.ID
	t.fieldMap["code"] = t.Code
	t.fieldMap["status"] = t.Status
	t.fieldMap["orderItemId"] = t.OrderItemID
	t.fieldMap["redeemedAt"] = t.RedeemedAt
	t.fieldMap["redeemedById"] = t.RedeemedByID
	t.fieldMap["createdAt"] = t.CreatedAt
	t.fieldMap["updatedAt"] = t.UpdatedAt
}

func (t ticketCode) clone(db *gorm.DB) ticketCode {
	t.ticketCodeDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t ticketCode) replaceDB(db *gorm.DB) ticketCode {
	t.ticketCodeDo.ReplaceDB(db)
	return t
}

type ticketCodeDo struct{ gen.DO }

type ITicketCodeDo interface {
	gen.SubQuery
	Debug() ITicketCodeDo
	WithContext(ctx context.Context) ITicketCodeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITicketCodeDo
	WriteDB() ITicketCodeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITicketCodeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITicketCodeDo
	Not(conds ...gen.Condition) ITicketCodeDo
	Or(conds ...gen.Condition) ITicketCodeDo
	Select(conds ...field.Expr) ITicketCodeDo
	Where(conds ...gen.Condition) ITicketCodeDo
	Order(conds ...field.Expr) ITicketCodeDo
	Distinct(cols ...field.Expr) ITicketCodeDo
	Omit(cols ...field.Expr) ITicketCodeDo
	Join(table schema.Tabler, on ...field.Expr) ITicketCodeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITicketCodeDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITicketCodeDo
	Group(cols ...field.Expr) ITicketCodeDo
	Having(conds ...gen.Condition) ITicketCodeDo
	Limit(limit int) ITicketCodeDo
	Offset(offset int) ITicketCodeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITicketCodeDo
	Unscoped() ITicketCodeDo
	Create(values ...*model.TicketCode) error
	CreateInBatches(values []*model.TicketCode, batchSize int) error
	Save(values ...*model.TicketCode) error
	First() (*model.TicketCode, error)
	Take() (*model.TicketCode, error)
	Last() (*model.TicketCode, error)
	Find() ([]*model.TicketCode, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TicketCode, err error)
	FindInBatches(result *[]*model.TicketCode, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TicketCode) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITicketCodeDo
	Assign(attrs ...field.AssignExpr) ITicketCodeDo
	Joins(fields ...field.RelationField) ITicketCodeDo
	Preload(fields ...field.RelationField) ITicketCodeDo
	FirstOrInit() (*model.TicketCode, error)
	FirstOrCreate() (*model.TicketCode, error)
	FindByPage(offset int, limit int) (result []*model.TicketCode, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITicketCodeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t ticketCodeDo) Debug() ITicketCodeDo {
	return t.withDO(t.DO.Debug())
}

func (t ticketCodeDo) WithContext(ctx context.Context) ITicketCodeDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t ticketCodeDo) ReadDB() ITicketCodeDo {
	return t.Clauses(dbresolver.Read)
}

func (t ticketCodeDo) WriteDB() ITicketCodeDo {
	return t.Clauses(dbresolver.Write)
}

func (t ticketCodeDo) Session(config *gorm.Session) ITicketCodeDo {
	return t.withDO(t.DO.Session(config))
}

func (t ticketCodeDo) Clauses(conds ...clause.Expression) ITicketCodeDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t ticketCodeDo) Returning(value interface{}, columns ...string) ITicketCodeDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t ticketCodeDo) Not(conds ...gen.Condition) ITicketCodeDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t ticketCodeDo) Or(conds ...gen.Condition) ITicketCodeDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t ticketCodeDo) Select(conds ...field.Expr) ITicketCodeDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t ticketCodeDo) Where(conds ...gen.Condition) ITicketCodeDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t ticketCodeDo) Order(conds ...field.Expr) ITicketCodeDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t ticketCodeDo) Distinct(cols ...field.Expr) ITicketCodeDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t ticketCodeDo) Omit(cols ...field.Expr) ITicketCodeDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t ticketCodeDo) Join(table schema.Tabler, on ...field.Expr) ITicketCodeDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t ticketCodeDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITicketCodeDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t ticketCodeDo) RightJoin(table schema.Tabler, on ...field.Expr) ITicketCodeDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t ticketCodeDo) Group(cols ...field.Expr) ITicketCodeDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t ticketCodeDo) Having(conds ...gen.Condition) ITicketCodeDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t ticketCodeDo) Limit(limit int) ITicketCodeDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t ticketCodeDo) Offset(offset int) ITicketCodeDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t ticketCodeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITicketCodeDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t ticketCodeDo) Unscoped() ITicketCodeDo {
	return t.withDO(t.DO.Unscoped())
}

func (t ticketCodeDo) Create(values ...*model.TicketCode) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t ticketCodeDo) CreateInBatches(values []*model.TicketCode, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t ticketCodeDo) Save(values ...*model.TicketCode) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t ticketCodeDo) First() (*model.TicketCode, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TicketCode), nil
	}
}

func (t ticketCodeDo) Take() (*model.TicketCode, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TicketCode), nil
	}
}

func (t ticketCodeDo) Last() (*model.TicketCode, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TicketCode), nil
	}
}

func (t ticketCodeDo) Find() ([]*model.TicketCode, error) {
	result, err := t.DO.Find()
	return result.([]*model.TicketCode), err
}

func (t ticketCodeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TicketCode, err error) {
	buf := make([]*model.TicketCode, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t ticketCodeDo) FindInBatches(result *[]*model.TicketCode, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t ticketCodeDo) Attrs(attrs ...field.AssignExpr) ITicketCodeDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t ticketCodeDo) Assign(attrs ...field.AssignExpr) ITicketCodeDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t ticketCodeDo) Joins(fields ...field.RelationField) ITicketCodeDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t ticketCodeDo) Preload(fields ...field.RelationField) ITicketCodeDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t ticketCodeDo) FirstOrInit() (*model.TicketCode, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TicketCode), nil
	}
}

func (t ticketCodeDo) FirstOrCreate() (*model.TicketCode, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TicketCode), nil
	}
}

func (t ticketCodeDo) FindByPage(offset int, limit int) (result []*model.TicketCode, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t ticketCodeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t ticketCodeDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t ticketCodeDo) Delete(models ...*model.TicketCode) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *ticketCodeDo) withDO(do gen.Dao) *ticketCodeDo {
	t.DO = *do.(*gen.DO)
	return t
}
