// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend_go/model"
)

func newTransactionRecord(db *gorm.DB, opts ...gen.DOOption) transactionRecord {
	_transactionRecord := transactionRecord{}

	_transactionRecord.transactionRecordDo.UseDB(db, opts...)
	_transactionRecord.transactionRecordDo.UseModel(&model.TransactionRecord{})

	tableName := _transactionRecord.transactionRecordDo.TableName()
	_transactionRecord.ALL = field.NewAsterisk(tableName)
	_transactionRecord.ID = field.NewString(tableName, "id")
	_transactionRecord.Amount = field.NewFloat64(tableName, "amount")
	_transactionRecord.PaymentMethod = field.NewString(tableName, "paymentMethod")
	_transactionRecord.Status = field.NewString(tableName, "status")
	_transactionRecord.IsManual = field.NewBool(tableName, "isManual")
	_transactionRecord.ManualMethod = field.NewString(tableName, "manualMethod")
	_transactionRecord.PaymentProofURL = field.NewString(tableName, "paymentProofUrl")
	_transactionRecord.ProofUploadedAt = field.NewTime(tableName, "proofUploadedAt")
	_transactionRecord.VerifiedAt = field.NewTime(tableName, "verifiedAt")
	_transactionRecord.VerifiedByID = field.NewString(tableName, "verifiedById")
	_transactionRecord.RejectionNote = field.NewString(tableName, "rejectionNote")
	_transactionRecord.RawMidtrans = field.NewString(tableName, "rawMidtrans")
	_transactionRecord.ExternalID = field.NewString(tableName, "externalId")
	_transactionRecord.PaymentURL = field.NewString(tableName, "paymentUrl")
	_transactionRecord.ExpiresAt = field.NewTime(tableName, "expiresAt")
	_transactionRecord.OrderID = field.NewString(tableName, "orderId")
	_transactionRecord.CreatedAt = field.NewTime(tableName, "createdAt")

	_transactionRecord.fillFieldMap()

	return _transactionRecord
}

type transactionRecord struct {
	transactionRecordDo

	ALL             field.Asterisk
	ID              field.String
	Amount          field.Float64
	PaymentMethod   field.String
	Status          field.String
	IsManual        field.Bool
	ManualMethod    field.String
	PaymentProofURL field.String
	ProofUploadedAt field.Time
	VerifiedAt      field.Time
	VerifiedByID    field.String
	RejectionNote   field.String
	RawMidtrans     field.String
	ExternalID      field.String
	PaymentURL      field.String
	ExpiresAt       field.Time
	OrderID         field.String
	CreatedAt       field.Time

	fieldMap map[string]field.Expr
}

func (t transactionRecord) Table(newTableName string) *transactionRecord {
	t.transactionRecordDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t transactionRecord) As(alias string) *transactionRecord {
	t.transactionRecordDo.DO = *(t.transactionRecordDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *transactionRecord) updateTableName(table string) *transactionRecord {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewString(table, "id")
	t.Amount = field.NewFloat64(table, "amount")
	t.PaymentMethod = field.NewString(table, "paymentMethod")
	t.Status = field.NewString(table, "status")
	t.IsManual = field.NewBool(table, "isManual")
	t.ManualMethod = field.NewString(table, "manualMethod")
	t.PaymentProofURL = field.NewString(table, "paymentProofUrl")
	t.ProofUploadedAt = field.NewTime(table, "proofUploadedAt")
	t.VerifiedAt = field.NewTime(table, "verifiedAt")
	t.VerifiedByID = field.NewString(table, "verifiedById")
	t.RejectionNote = field.NewString(table, "rejectionNote")
	t.RawMidtrans = field.NewString(table, "rawMidtrans")
	t.ExternalID = field.NewString(table, "externalId")
	t.PaymentURL = field.NewString(table, "paymentUrl")
	t.ExpiresAt = field.NewTime(table, "expiresAt")
	t.OrderID = field.NewString(table, "orderId")
	t.CreatedAt = field.NewTime(table, "createdAt")

	t.fillFieldMap()

	return t
}

func (t *transactionRecord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *transactionRecord) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 17)
	t.fieldMap["id"] = t.ID
	t.fieldMap["amount"] = t.Amount
	t.fieldMap["paymentMethod"] = t.PaymentMethod
	t.fieldMap["status"] = t.Status
	t.fieldMap["isManual"] = t.IsManual
	t.fieldMap["manualMethod"] = t.ManualMethod
	t.fieldMap["paymentProofUrl"] = t.PaymentProofURL
	t.fieldMap["proofUploadedAt"] = t.ProofUploadedAt
	t.fieldMap["verifiedAt"] = t.VerifiedAt
	t.fieldMap["verifiedById"] = t.VerifiedByID
	t.fieldMap["rejectionNote"] = t.RejectionNote
	t.fieldMap["rawMidtrans"] = t.RawMidtrans
	t.fieldMap["externalId"] = t.ExternalID
	t.fieldMap["paymentUrl"] = t.PaymentURL
	t.fieldMap["expiresAt"] = t.ExpiresAt
	t.fieldMap["orderId"] = t.OrderID
	t.fieldMap["createdAt"] = t.CreatedAt
}

func (t transactionRecord) clone(db *gorm.DB) transactionRecord {
	t.transactionRecordDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t transactionRecord) replaceDB(db *gorm.DB) transactionRecord {
	t.transactionRecordDo.ReplaceDB(db)
	return t
}

type transactionRecordDo struct{ gen.DO }

type ITransactionRecordDo interface {
	gen.SubQuery
	Debug() ITransactionRecordDo
	WithContext(ctx context.Context) ITransactionRecordDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITransactionRecordDo
	WriteDB() ITransactionRecordDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITransactionRecordDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITransactionRecordDo
	Not(conds ...gen.Condition) ITransactionRecordDo
	Or(conds ...gen.Condition) ITransactionRecordDo
	Select(conds ...field.Expr) ITransactionRecordDo
	Where(conds ...gen.Condition) ITransactionRecordDo
	Order(conds ...field.Expr) ITransactionRecordDo
	Distinct(cols ...field.Expr) ITransactionRecordDo
	Omit(cols ...field.Expr) ITransactionRecordDo
	Join(table schema.Tabler, on ...field.Expr) ITransactionRecordDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITransactionRecordDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITransactionRecordDo
	Group(cols ...field.Expr) ITransactionRecordDo
	Having(conds ...gen.Condition) ITransactionRecordDo
	Limit(limit int) ITransactionRecordDo
	Offset(offset int) ITransactionRecordDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITransactionRecordDo
	Unscoped() ITransactionRecordDo
	Create(values ...*model.TransactionRecord) error
	CreateInBatches(values []*model.TransactionRecord, batchSize int) error
	Save(values ...*model.TransactionRecord) error
	First() (*model.TransactionRecord, error)
	Take() (*model.TransactionRecord, error)
	Last() (*model.TransactionRecord, error)
	Find() ([]*model.TransactionRecord, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TransactionRecord, err error)
	FindInBatches(result *[]*model.TransactionRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TransactionRecord) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITransactionRecordDo
	Assign(attrs ...field.AssignExpr) ITransactionRecordDo
	Joins(fields ...field.RelationField) ITransactionRecordDo
	Preload(fields ...field.RelationField) ITransactionRecordDo
	FirstOrInit() (*model.TransactionRecord, error)
	FirstOrCreate() (*model.TransactionRecord, error)
	FindByPage(offset int, limit int) (result []*model.TransactionRecord, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITransactionRecordDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t transactionRecordDo) Debug() ITransactionRecordDo {
	return t.withDO(t.DO.Debug())
}

func (t transactionRecordDo) WithContext(ctx context.Context) ITransactionRecordDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t transactionRecordDo) ReadDB() ITransactionRecordDo {
	return t.Clauses(dbresolver.Read)
}

func (t transactionRecordDo) WriteDB() ITransactionRecordDo {
	return t.Clauses(dbresolver.Write)
}

func (t transactionRecordDo) Session(config *gorm.Session) ITransactionRecordDo {
	return t.withDO(t.DO.Session(config))
}

func (t transactionRecordDo) Clauses(conds ...clause.Expression) ITransactionRecordDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t transactionRecordDo) Returning(value interface{}, columns ...string) ITransactionRecordDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t transactionRecordDo) Not(conds ...gen.Condition) ITransactionRecordDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t transactionRecordDo) Or(conds ...gen.Condition) ITransactionRecordDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t transactionRecordDo) Select(conds ...field.Expr) ITransactionRecordDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t transactionRecordDo) Where(conds ...gen.Condition) ITransactionRecordDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t transactionRecordDo) Order(conds ...field.Expr) ITransactionRecordDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t transactionRecordDo) Distinct(cols ...field.Expr) ITransactionRecordDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t transactionRecordDo) Omit(cols ...field.Expr) ITransactionRecordDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t transactionRecordDo) Join(table schema.Tabler, on ...field.Expr) ITransactionRecordDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t transactionRecordDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITransactionRecordDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t transactionRecordDo) RightJoin(table schema.Tabler, on ...field.Expr) ITransactionRecordDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t transactionRecordDo) Group(cols ...field.Expr) ITransactionRecordDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t transactionRecordDo) Having(conds ...gen.Condition) ITransactionRecordDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t transactionRecordDo) Limit(limit int) ITransactionRecordDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t transactionRecordDo) Offset(offset int) ITransactionRecordDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t transactionRecordDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITransactionRecordDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t transactionRecordDo) Unscoped() ITransactionRecordDo {
	return t.withDO(t.DO.Unscoped())
}

func (t transactionRecordDo) Create(values ...*model.TransactionRecord) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t transactionRecordDo) CreateInBatches(values []*model.TransactionRecord, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t transactionRecordDo) Save(values ...*model.TransactionRecord) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t transactionRecordDo) First() (*model.TransactionRecord, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TransactionRecord), nil
	}
}

func (t transactionRecordDo) Take() (*model.TransactionRecord, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TransactionRecord), nil
	}
}

func (t transactionRecordDo) Last() (*model.TransactionRecord, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TransactionRecord), nil
	}
}

func (t transactionRecordDo) Find() ([]*model.TransactionRecord, error) {
	result, err := t.DO.Find()
	return result.([]*model.TransactionRecord), err
}

func (t transactionRecordDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TransactionRecord, err error) {
	buf := make([]*model.TransactionRecord, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t transactionRecordDo) FindInBatches(result *[]*model.TransactionRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t transactionRecordDo) Attrs(attrs ...field.AssignExpr) ITransactionRecordDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t transactionRecordDo) Assign(attrs ...field.AssignExpr) ITransactionRecordDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t transactionRecordDo) Joins(fields ...field.RelationField) ITransactionRecordDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t transactionRecordDo) Preload(fields ...field.RelationField) ITransactionRecordDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t transactionRecordDo) FirstOrInit() (*model.TransactionRecord, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TransactionRecord), nil
	}
}

func (t transactionRecordDo) FirstOrCreate() (*model.TransactionRecord, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TransactionRecord), nil
	}
}

func (t transactionRecordDo) FindByPage(offset int, limit int) (result []*model.TransactionRecord, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t transactionRecordDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t transactionRecordDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t transactionRecordDo) Delete(models ...*model.TransactionRecord) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *transactionRecordDo) withDO(do gen.Dao) *transactionRecordDo {
	t.DO = *do.(*gen.DO)
	return t
}
